### ISSUE TITLE
Support socket.io channels in Sockend

### ISSUE THREAD

**Issue by orrgal1** [dashersw/cote#101]
Haven't seen any docs about this being supported. Is it?
I have a common scenario  where my users are connected via socket.io but each is subscribed to specific channels which allows me to control who gets which events. If I set it up with sockend it would seem there is no way to do this.

**Comment by dashersw** [comment]
There's no support for channels as it doesn't make sense in a cote environment; but cote supports namespaces. If there's a need for such selective broadcast to certain clients, a custom implementation could be done that iterates over all connected sockets and if they meet a certain criteria, sends them the message.

**Comment by dashersw** [comment]
Fixed in #104
