### ISSUE TITLE
Text mistakes @ http://cote.js.org/

### ISSUE THREAD

**Issue by GHNewbiee** [dashersw/cote#105]
Hi,

I have found two text mistakes at http://cote.js.org/.

In both cases:

> Click to see the complete conversion-service.js file.

1st
```js const cote = require('cote'); const responder = new cote.Requester({ name: 'currency conversion responder' }); const rates = { usd_eur: 0.91, eur_usd: 1.10 }; responder.on('convert', (req, cb) => { cb(req.amount * rates[`${req.from}_${req.to}`]); }); ```  and

2nd
-```js const cote = require('cote'); const responder = new cote.Requester({ name: 'currency conversion responder' }); const subscriber = new cote.Subscriber({ name: 'arbitration subscriber' }); const rates = { usd_eur: 0.91, eur_usd: 1.10 }; subscriber.on('update rate', (update) => { rates[update.currencies] = update.rate; }); responder.on('convert', (req, cb) => { cb(req.amount * rates[`${req.from}_${req.to}`]); }); ``` 

the `new cote.Requester({...` should be `new cote.Responder({...`

Tia

**Comment by dashersw** [comment]
Thank you, fixed.
