### ISSUE TITLE
Properly handle network-layer errors

### ISSUE THREAD

**Issue by gustavomassa** [dashersw/cote#109]
Hello,

Are there any events to handle errors and network-layer errors? 
I made a simple test when two microservices were communicating, one broadcasting messages to a specific topic and the other service subscribed to that topic and receiving messages every 100ms. 

Then I removed the network cable for a few seconds and re-connected the  cable again, after that the communication stopped and vscode started using about 90% of CPU. I did no see any errors/exceptions or unhandled exceptions during the test execution.
Any ideas how I could handle errors and network layer errors?

**Comment by dashersw** [comment]
This in fact shouldn't have been the case. Have you identified a similar issue in production (not running in vscode, for example?)
