### ISSUE TITLE
Heroku and Procfile

### ISSUE THREAD

**Issue by enricodeleo** [dashersw/cote#110]
Hello! Thank you for this great tool!
I was trying to deploy a new express app with microservices based on `cote` thinking that if I'd used Procfile (with one process per microservice) and redis for discovery I'd have got a bleeding edge new microservice platform but apparently that's not the case.
Has anyone tried to accomplish the same thing? Any hint?

**Comment by super-ienien** [comment]
What do you mean exactly ?

**Comment by dashersw** [comment]
I'm pretty sure it won't work on Heroku. Even though redis is used for discovery, cote expects machines to be on the same network and to be identifiable.

**Comment by drubin** [comment]
You might be able to make use of https://www.heroku.com/private-spaces and + https://www.heroku.com/dynos/private-spaces + redis with the  `DISCOVERY_HOSTNAME` env variable.

There are pretty strict limits on these "100 dynos". So you might reach that pretty soon if you are deploying a bunch of separate cote services. I also don't think Heroku's pricing model lends its self well to using cote.

**Comment by enricodeleo** [comment]
thank you @drubin I don't know how `DISCOVERY_HOSTNAME` works, what should I set for it?

**Comment by super-ienien** [comment]
You can for exemple set the DISCOVERY_HOSTNAME to the Host IP’s of your microservice.

My understanding of this env car is that it will be used by the auto discovery system to let know other services how to reach your service. It is useful when auto discovery is not able to retrieve the microservice host adress by itself.

you also should set the COTE_USE_HOST_NAMES var to true if you wan’t DISCOVERY_HOSTNAME to work

**Comment by enricodeleo** [comment]
@super-anien I think on PaaS you get different ips and hosts hence my question (and why I thought redis was there)

**Comment by super-ienien** [comment]
Cote need a network to work, virtual or real. If your services do not run in containers that can communicate each other with a network then I don’t think cote will work...

But like you a first thought that redis was used as a message broadcaster. That’s not the case right now

**Comment by super-ienien** [comment]
If your services run on containers that are on the same network and that you can now the ip’s of your containers you should be able to set the DISCOVERY_HOSTNAME to your container’s IP. The ports 8xxx should be opened for your services be able to connect each other’s. Cote start assigning port at 8000 and increment the port number for each connection

**Comment by enricodeleo** [comment]
Thanks and yes, I understood that redis is for discovery and yes containers are visible each other. After a few tests I saw that during the app bootstrap node-discover read hostname as the internal id of the container (e.g. '9290e05f-dff3-4af4-bdaf-0b28f937a9d8') and not the hostname that is reacheable by other containers.

**Comment by super-ienien** [comment]
Yes that’s exactly why you should set the HOSTNAME manually via the env var DISCOVERY_HOSTNAME. You can monitor your redis server to check if the auto discovery system is using your manually set value. You’ll see that in the hello messages

**Comment by super-ienien** [comment]
yes and if it doesn't work, check that your 8xxx ports are opened and try to add COTE_USE_HOST_NAMES=true

**Comment by enricodeleo** [comment]
Thank you for all the suggestions. It eventually worked!

**Comment by dashersw** [comment]
@enricodeleo that is wonderful! Could you share some example code / approach so we can add it to the README / Wiki?

**Comment by dashersw** [comment]
You can pass in a port parameter when you create your components as in

```
const cote = require('cote');
new cote.Responder({ name: 'responder', port: 3000 });
```

This will try to use port 3000, and if it's not available, will try 3001 and so on. Publishers and Responders are the one who are creating the servers, so this port config only applies to them.

**Comment by drubin** [comment]
Just a heads up from the docs https://flynn.io/docs/apps#service-discovery 

> Flynn automatically registers each web process type in service discovery for internal requests that >do not go through the router. The service discovery entries are available via DNS. The pattern $APPNAME-$PROCTYPE.discoverd is used for the DNS name, for example myapp-web.discoverd and myapp-admin-web.discoverd. This feature can be used to communicate internally between apps and processes.

It seems like this behaviours like Heroku does as well. The `DISCOVERY_HOSTNAME` hostname you are setting is linked to the "SERVICE" endpoint which will be a single host if the scale is 1. but will contain 2 hosts if you scale it 2. This is why it works with the default setup above.

Cote isn't designed to be put behind a load balancer or DNS record that points to multiple IP's.

I just thought I would highlight this so if you run into issues with the scaling features not working 100% you at least have a reference point.

**Comment by enricodeleo** [comment]
thank you @dashersw I did not notice this feature.

@drubin does it means that I cannot scale to more than 1 instance of each microservice?

**Comment by drubin** [comment]
@enricodeleo That is my assumption based on their docs and the fact they use DNS to balance between machines. Although I have never actually used Flynn

I am fairly sure you could get access to the underlying IP address of the container/service and use that, but that is something you will have to check and get it from code.

But again you won't be able to pass it in as an ENV variable as you are doing there (those are shared between each instance).

Suggest trying hostname, or ip lookups.
