### ISSUE TITLE
Redis communication between Requester and Responder

### ISSUE THREAD

**Issue by AndriiLa** [dashersw/cote#112]
Hello.

Please, could you provide next information: how to configure/use Redis for sending/receiving message between Responder and Requester?

When I configure Responder/Requester:

const templateResponder = new cote.Responder({
    name: 'my responder'
     key: 'my key',
     namespace: 'my namespace'
},
    {
        redis: {
            host: 'localhost'
        }
    });

It only works for auto discovery micro services. But I need to send/receive data over Redis too (without HTTP as a transport).

Thank you in advance.

**Comment by dashersw** [comment]
Redis is only used for discovery. Sending / receiving data happens over bespoke TCP server / client communication and not through HTTP. But unfortunately there's no way to send messages over redis.

**Comment by AndriiLa** [comment]
First of all, thank you for your answer.

But, I need to send/receive large binary data (1-5 MB) between microservices.
It seems, cote can only work with JSON data.
Can I send raw binary data between Requester and Responder?

**Comment by dashersw** [comment]
Currently it's not supported, but we should work on adding binary support. It's supported by the underlying library axon, but cote only works with JSON. Of course, you could always base64 your binary.
