### ISSUE TITLE
Active monitoring

### ISSUE THREAD

**Issue by enricodeleo** [dashersw/cote#114]
This one may be a suggestion: I was wondering if I can create an active monitoring. I mean I woud like to put in place a service much like the monitor tool provided by cote but that actively detect services that go down and notify the developer somehow (email, slack, whatever). 

Has someone tried to implement such a feature?

**Comment by dashersw** [comment]
Of course! In fact the built-in monitoring tool also uses the Monitor component. You can take it as an example and build any notification mechanism in. In fact, it would be awesome if you could open source it / contribute it to cote.
