### ISSUE TITLE
Multiple cote instances sharing redis stalls

### ISSUE THREAD

**Issue by Celadora** [dashersw/cote#115]
It would be nice to be able to use the same redis instance for multiple cote clients. We have a microservice pattern that uses cote for interservice communication, but if we use the same redis instance for more than one service: Cote stalls.

**Comment by dashersw** [comment]
Could you share an example? This shouldn't have been the case. Are you making use of environments and keys? Cote already comes with several layers of separation / abstraction between services. When you're instantiating services, passing in an environment configuration like `test` or `production` will lead to segregation between services. you can also use `COTE_ENV` process environment variable to dictate the environment to run the service in, without touching the code.

If these don't work for you, I'd love to have a look if you share some example code.
