### ISSUE TITLE
How to know how many requests each requester has to send

### ISSUE THREAD

**Issue by brunofigalveskk** [dashersw/cote#116]
Hi, I'd like to know how many requests each requester has to send? Cote has any monitor to know this information or function to get this?

**Comment by dashersw** [comment]
If you are wondering if there are any messages in the queue in a requester, you can use `requester.sock.queue` array and check for its length. When there are no matching responders, you will see that this queue will grow. Whenever a responder is available, this queue will mostly be empty.
