### ISSUE TITLE
Environment property

### ISSUE THREAD

**Issue by gustavomassa** [dashersw/cote#117]
Hello,

I need help converting the normal import of cote using require with module properties.
`const cote = require('cote')({ environment: 'developer-2' });`

```
import * as cote from 'cote';

export class ServiceController {
    private static _instance: ServiceController;
    private discoveryOptions: cote.DiscoveryOptions;
    private res: cote.Responder;
    private sub: cote.Subscriber;
```

Using import, how can I pass the environment option to cote module since we're not instantiating a cote object?

**Comment by rafaismyname** [comment]
```
import cote from 'cote';

const Cote = cote({ environment: 'developer-2' });
```

**Comment by dashersw** [comment]
Indeed the best way is to use the `COTE_ENV` environment variable.
