### ISSUE TITLE
Will cote work between sites on different networks?

### ISSUE THREAD

**Issue by orrgal1** [dashersw/cote#126]
Not really an issue, more of a question...
I want to use cote for syncing data between sites. These sites run on completely different networks and can access each other via IP. Assuming I set up discovery via redis, will the rest of cote function properly? After discovery, will the the cote nodes be able to talk to each other?
Thanks

**Comment by dashersw** [comment]
Yes. Depending on the network configuration, you might need to configure the host name environment variable, but everything else will work.

**Comment by orrgal1** [comment]
Great, thanks!
