### ISSUE TITLE
Support typescript

### ISSUE THREAD

**Issue by duongvanba** [dashersw/cote#129]
### Typescirpt decorator for CoteJS
   I have built a Typescript library for CoteJS, it use typesciprt decorator to fast create microservice code
(https://github.com/duongvanba/ts-cote)

- Subcriber, publisher, requester and responder are define in class with decorator
- Cote key of subcriber and publisher are event class name
- Cote key of responder and requester are define in responder extends class
- Responder can stop and restart listen requester anytime

**Comment by makepost** [comment]
Hi. Why do you remove my MIT license and remove me from package.json if you base it on my [nyan-cote](https://github.com/makepost/nyan-cote) project and keep my commits in history?

**Comment by dashersw** [comment]
This can be a separate project / repo, but cote will not support any of the TS features other than code completion based on types for editors.

**Comment by duongvanba** [comment]
#makepost sorry I will update son 
I'm not good about git
