### ISSUE TITLE
Pattern matching like seneca?

### ISSUE THREAD

**Issue by DayBr3ak** [dashersw/cote#130]
Does Côte allow pattern matching events+payload of some sorts?

in seneca you can define services as such

```js

//first service
seneca.add({cmd: 'salestax', country: 'US'}, handler)

// other service
seneca.add({cmd: 'salestax', country: 'DE'}, handler)


// client
seneca.act('cmd:salestax,net:100,country:DE', function (err, result) {
  console.log('DE: ' + result.total)
})
seneca.act('cmd:salestax,net:100,country:US,state:NY', function (err, result) {
  console.log('US,NY: ' + result.total)
})
```

It allows some nice decoupling, I was wondering how one would achieve such behavior in Côte?

**Comment by dashersw** [comment]
I think pattern matching approach like this creates more ambiguity than it brings any real world benefit when it comes to scaling out the number of services.

cote doesn't support any pattern matching, however, you can use keys to achieve a similar result.

I think pattern matching approach like this creates more ambiguity than it brings any real world benefit when it comes to scaling out the number of services.

cote doesn't support any pattern matching, however, you can use keys to achieve a similar result.

`salestax-us-service.js`
```js
const cote = require('cote')
const responder = new cote.Responder({ name: 'salestax-us responder', key: 'salestax-us' })
responder.on('salestax', handler)
```

`salestax-de-service.js`
```js
const cote = require('cote')
const responder = new cote.Responder({ name: 'salestax-de responder', key: 'salestax-de' })
responder.on('salestax', handler)
```

`client.js`
```js
const cote = require('cote')
const usRequester = new cote.Requester({ name: 'salestax-us client', key: 'salestax-us' })
const deRequester = new cote.Requester({ name: 'salestax-de client', key: 'salestax-de' })

const res1 = await deRequester.send({ type: 'salestax', net: 100 })
console.log(`DE: ${res.total}`)

const res2 = await usRequester.send({ type: 'salestax', net: 100, state: 'NY' })
console.log(`US,NY: ${res.total}`)
```

**Comment by DayBr3ak** [comment]
Thank you for your quick and detailed answer. 
I'm not really convinced this solution scales as you would need to introduce as many responders as you would want to extend yours features. It also mean go back and modifying the client service each time you introduce a new service, which defeats decoupling.

Thanks for your time.
