### ISSUE TITLE
 Problem to connect between Responders and Requesters with Redis

### ISSUE THREAD

**Issue by brunofigalveskk** [dashersw/cote#134]
I'm getting a problem to connect between Responders and Requesters. When I make a requester from a Reponder to a Requester the service throw a new log in both but don't receive anything.

The redis server is running in Requester server.

**Comment by dashersw** [comment]
Where are you running the machines? Have you tried the answer to your previous question here https://github.com/dashersw/cote/issues/131#issuecomment-427798054 ? Setting the `DISCOVERY_HOSTNAME` right would make sure the services discover each other. Then also they need to be able to communicate with open ports — if you're locking down the machines' ports, it might not work.

**Comment by dashersw** [comment]
`DISCOVERY_HOSTNAME` shouldn't be the IP address of the redis server, but rather the IP addresses of servers where your application is running.

if your requester is running on server A with IP 10.0.1.5, then DISCOVERY_HOSTNAME for that requester should be 10.1.1.5.

if your responder is running on server B with IP 10.0.1.6, then DISCOVERY_HOSTNAME for that responder should be 10.0.1.6.

**Comment by brunofigalveskk** [comment]
Ok. I already set `DISCOVERY_HOSTNAME` as you said. But I'm still having the same problem. When I make a request I see in both, Responder and Request logs, but then Request goes to offline.
I already try and I have remote access to Redis server in server "A". So I think that something is missing.

In server A where I have the requesters and redis I setup environment variable:
COTE_DISCOVERY_REDIS=true
COTE_DISCOVERY_REDIS_HOST=10.0.1.5
COTE_DISCOVERY_REDIS_PORT=6379

In server B:
COTE_DISCOVERY_REDIS=false
COTE_DISCOVERY_REDIS_HOST=10.0.1.5
COTE_DISCOVERY_REDIS_PORT=6379

**Comment by brunofigalveskk** [comment]
I already resolved. Some environment variable not set. Thank you for your help.

**Comment by brunofigalveskk** [comment]
I'm having a problem with the server A... I have a lot of outgoing traffic and when I verify my connections with the Redis. I have a lot of connections, I think that services does not close the connection or don't check for an available connection. Could you help me with this?

**Comment by pelzerim** [comment]
> I'm having a problem with the server A... I have a lot of outgoing traffic and when I verify my connections with the Redis. I have a lot of connections, I think that services does not close the connection or don't check for an available connection. Could you help me with this?

It looks like you are creating new requesters/responders for every request instead of reusing them. Can you please provide relevant code, so i can reproduce it?

Also, could you explain what environment variable was not set, so in the future someone else can find help here? :)

**Comment by brunofigalveskk** [comment]
Yes I was creating new requesters/responders for every request and now my outgoing traffic stabilized.
The issue related with the environment variable I thinks it was related with PM2.

> > I'm having a problem with the server A... I have a lot of outgoing traffic and when I verify my connections with the Redis. I have a lot of connections, I think that services does not close the connection or don't check for an available connection. Could you help me with this?
> 
> It looks like you are creating new requesters/responders for every request instead of reusing them. Can you please provide relevant code, so i can reproduce it?
> 
> Also, could you explain what environment variable was not set, so in the future someone else can find help here? :)
