### ISSUE TITLE
How to catch inited event in order to get uuid

### ISSUE THREAD

**Issue by duongvanba** [dashersw/cote#135]
Hi
Thank you for your awesome library
I'm building my small product with Cote.

I have 2 services, many worker and 1 composer. When my worker service online, it send its status working to composer. But if worker restart, it send again to composer. So I decide to send worker uuid together with message to composer

But current I must use setTimeout to wait worker started to get uuid, can you show me the code detect when worker service started?

Thanks you

**Comment by duongvanba** [comment]
hus

**Comment by pelzerim** [comment]
Can you provide relevant code, so we can reproduce/investigate?

**Comment by pelzerim** [comment]
All components emit the `cote:added` event that contains information about them:
`responder.on('cote:added', function(data){
    console.log(data.id)
})`
Did this answer your question?
