### ISSUE TITLE
Create ENV variable for log options

### ISSUE THREAD

**Issue by matejthetree** [dashersw/cote#139]
I will tackle this, 

putting the issue here.

```
there are three advertisement options:

```log: true,
helloLogsEnabled: true,
statusLogsEnabled: true,```
```

**Comment by knoxcard** [comment]
what about controlling logging from a parameter standpoint?

**Comment by matejthetree** [comment]
I was about to implement this but I am super busy to finish it.

Tomorrow I will make the pull request with the code.

**Comment by dashersw** [comment]
@matejthetree I have implemented it in a more generic way, I hope you don't mind.

**Comment by matejthetree** [comment]
Perfect
