### ISSUE TITLE
what if the subscriber is not available at the time? 

### ISSUE THREAD

**Issue by inamvar** [dashersw/cote#140]
In case of an unavailable subscriber at the time, does publisher guarantee that the subscriber will get messages when being available later? like what we have in ActiveMQ?

**Comment by dashersw** [comment]
No, publishers use a fire and forget mechanism. If you want delivery guarantee, you should use a requester / responder pair.

**Comment by matejthetree** [comment]
You should use requester to get initial or current data, and then publisher
to stay in sync with any changes.
