### ISSUE TITLE
Can responder instance be automatically created if the existing ones are busy?

### ISSUE THREAD

**Issue by dotm** [dashersw/cote#141]
Hello there. I want to ask a question.

If the existing responders for an event are all busy doing heavy computation and there are unhandled requests waiting, is it possible to automatically create a new responder instance to lessen the load?
I tried creating new instance programmatically but get stuck because I don't know how to get the total number unhandled request or how to trigger an event when a responder is taking too long to respond.

Thanks in advance.

**Comment by dashersw** [comment]
Hi! Try checking out PendingBalancedRequester component, which is a specialized requester for keeping track of the number of pending requests a requester have for each responder it has. This is an alternative load-balancing technique to round-robin.

**Comment by knoxcard** [comment]
Have you tried the toobusy js module?  I use it in my middleware inside my app logic to control server overload.

https://www.npmjs.com/package/toobusy-js
