### ISSUE TITLE
my services failed to connect using redis as central discovery in swarm mode

### ISSUE THREAD

**Issue by aaami1ster** [dashersw/cote#145]
when using redis as central discovery tool it works for the first time. but after a while it fails with this error. any help please
> my-service.1.j98uvp7sf1oc@node-1    | {"error":{"command":"INFO","code":"NOAUTH"},"level":"error","message":"uncaughtException: Ready check failed: NOAUTH Authentication required.\nReplyError: Ready check failed: NOAUTH Authentication required.\n    at parseError (/src/node_modules/redis-parser/lib/parser.js:193:12)\n    at parseType (/src/node_modules/redis-parser/lib/parser.js:303:14)","stack":"ReplyError: Ready check failed: NOAUTH Authentication required.\n    at parseError (/src/node_modules/redis-parser/lib/parser.js:193:12)\n    at parseType (/src/node_modules/redis-parser/lib/parser.js:303:14)","exception":true,"date":"Sat Dec 29 2018 23:56:50 GMT+0200 (EET)","process":{"pid":1,"uid":0,"gid":0,"cwd":"/src","execPath":"/usr/local/bin/node","version":"v8.14.0","argv":["/usr/local/bin/node","/src/quotation-service/app.js"],"memoryUsage":{"rss":51236864,"heapTotal":33980416,"heapUsed":18967552,"external":831037}},"os":{"loadavg":[14.76416015625,4.69873046875,1.64111328125],"uptime":1585019},"trace":[{"column":12,"file":"/src/node_modules/redis-parser/lib/parser.js","function":"parseError","line":193,"method":null,"native":false},{"column":14,"file":"/src/node_modules/redis-parser/lib/parser.js","function":"parseType","line":303,"method":null,"native":false}]}

**Comment by dashersw** [comment]
It looks like an authentication issue with your Redis server.
