### ISSUE TITLE
How to discover services?

### ISSUE THREAD

**Issue by georgyfarniev** [dashersw/cote#154]
Hello. Thank you for creating such useful library. I have simple question: is it possible to use it for multicast discovery, in similar manner as [bonjour](https://github.com/watson/bonjour)? Or at least make it possible to get response from all services for specific request, instead of single one. It would give possibility to send command like **discovery** and get replies from all services. Than would solve problem as well.

The use case is to display which services are currently running on specific page. It's also unclear how to achieve it from documentation via redis.

**Comment by dashersw** [comment]
Hello, you can definitely check the monitor component, which does a very similar thing. Each node already knows who’s online. Monitor components know every other component. If you don’t want to use the monitor component, the way to achieve this would be a tiny publisher in all services and a central subscriber that will gather everything.

**Comment by georgyfarniev** [comment]
@dashersw looks like exactly what I need, thank you. I will check it out soon.

**Comment by georgyfarniev** [comment]
@dashersw I apologize for reopening this ticket. I reviewed Monitor class, and it turns out it's what I need, except it prints data to standard output instead, but doesn't provide convenient API to retrieve this data programmaticaly (or I just missed something, because there's no detailed documentation for monitor?)

May you consider to accept pull request if I implement monitor as convenient class for programmatic usage?

**Comment by georgyfarniev** [comment]
Any updates on this? Usage of Configurable is inconvenient for code using cote and monitor with proper programmatic interface  is pretty essential thing to discover services. I just want to understand whether it’s acceptable by owner to have such component in addition, then create PR.

**Comment by dashersw** [comment]
Hi @georgyfarniev! Please see [this block of code](https://github.com/dashersw/cote/blob/master/src/monitoring-tool/index.js#L46-L96) on how to make use of the existing monitor component programmatically.

**Comment by dashersw** [comment]
You can use a discovery option to disable printing to the screen as well: `https://github.com/dashersw/cote/blob/master/src/components/monitor.js#L50`

**Comment by dashersw** [comment]
You would instantiate the monitor like 

```js
new cote.Monitor({ name: 'monitor' }, { disableScreen: true });
```

Hope this helps.

**Comment by georgyfarniev** [comment]
@dashersw thank you very much for rapid and detailed response! I will check out as soon as possible and let you know.

**Comment by georgyfarniev** [comment]
@dashersw it completely satisfied my needs. Thanks a lot!
