### ISSUE TITLE
Using cote with ufw

### ISSUE THREAD

**Issue by georgyfarniev** [dashersw/cote#156]
Hello. I tried to use **cote** on server with **ufw** on with server-specific settings, but cote doesn't work. How can I use cote with **ufw**? What ports should be available for correct operation of cote? This part is not covered in documentation, at least I was not able to find it. Thanks in advance.

**Comment by dashersw** [comment]
cote will dynamically allocate a TCP port number of 8000 as each service will get a new port, and UDP 5555.

**Comment by georgyfarniev** [comment]
@dashersw thank you. I just allowed TCP 8000 to 8100 from anywhere and UDP 5555 from anywhere, restarted all services and it still doesn't work. If I disable ufw, it works. Also I run services in PM2, if it does matter. What could I miss?

```
ufw status
Status: active

To                         Action      From
--                         ------      ----
5555/udp                   ALLOW       Anywhere
8000:8100/tcp              ALLOW       Anywhere
5555/udp (v6)              ALLOW       Anywhere (v6)
8000:8100/tcp (v6)         ALLOW       Anywhere (v6)
```

**Comment by dashersw** [comment]
Hello @georgyfarniev ! I'm sorry, the UDP port should be `12345`, and not `5555`.

**Comment by georgyfarniev** [comment]
@dashersw thank you very much. It solved my problem. I will try to create doc PR to cover this topic as well when I have time.
