### ISSUE TITLE
How to watch messages?

### ISSUE THREAD

**Issue by mr-kashif** [dashersw/cote#157]
How can I watch messages being passed from service to service from another service in my network?

example: I have a time service and a client that calls time service with a message. how can I intercept and watch the message being passed from another service?

**Comment by matejthetree** [comment]
The solution would be to use a publisher for sending message and than subscribing to the publisher on both services.

**Comment by dashersw** [comment]
The messages are exchanged over peer to peer connection, so unless, as @matejthetree suggests, you also publish all messages with a publisher, there’s no way to intercept them.

**Comment by mr-kashif** [comment]
So in this case I can just make a message router and make every service talk to it. Hence, keeping track.

**Comment by dashersw** [comment]
A centralized router is quite killing the point of microservices, though. It’s all about decentralization.

**Comment by mr-kashif** [comment]
@dashersw that's why I wanted to intercept and record passed messages. I was thinking of a possibility that we can extend tue monitoring tool to do so.

**Comment by dashersw** [comment]
This might be of help:

```js
const cote = require('cote');

const monitor = new cote.Monitor({ name: 'monitor' }, { disableScreen: true });

monitor.sock.on('message', console.log);
const requester = new cote.Requester({ name: 'requester' });

setTimeout(() => {
  const request = { type: 'hello' }
  requester.send(request);
  requester.monitorStatusPublisher.emit('message', request);
}, 2000);
```
