### ISSUE TITLE
Cannot connect multiple instances in AWS 

### ISSUE THREAD

**Issue by tericnexus** [dashersw/cote#159]
I have two AWS instances each running different microservice and I have used Redis for service discovery. When I run the code locally, my services are able to discover each other via Redis and I get triggered. But when I try to run the same code on 2 VM'S the services are getting discovered but the triggers are not sent.

To explain, I have taken currency conversion script from examples 

Responder on Server 1 

```

const cote = require('cote')({ redis: { url: 'redis://:pass@hostname:27015' } });
const responder = new cote.Responder({ name: 'currency conversion responder' });
const rates = { usd_eur: 0.91, eur_usd: 1.10 };
responder.on('convert', (req, cb) => { console.log('New Request'); cb(req.amount * rates[`${req.from}_${req.to}`]); });

```

Requester on Server 2
 
```
const cote = require('cote')({ redis: { url: 'redis://:pass@hostname:27015' } });
const requester = new cote.Requester({ name: 'currency conversion requester' });
const request = { type: 'convert', from: 'usd', to: 'eur', amount: 100 };
requester.send(request, (res) => { console.log(res); });

```

When I execute this on my computer as 2 seperate Node projects I get this response which is expected.

![Screenshot (5)](https://user-images.githubusercontent.com/6284338/55683527-533fd180-595e-11e9-89c3-af1c68ad515a.png)

On AWS instances I see this response

![Screenshot (6)](https://user-images.githubusercontent.com/6284338/55683531-5f2b9380-595e-11e9-8847-0489342ddb61.png)

I have tried executing the node project from Docker using this config

```
FROM node:10
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 8000
CMD [ "npm", "start" ]

```

I have also allowed outsider access on PORT 8000 for both VM inside AWS port rules, but still no output. 

Please let me know if I missed anything.

**Comment by dashersw** [comment]
Looking at the screenshots, it looks like service1 discovers other requesters as well. The problem might be in connection — try setting a `DISCOVERY_HOSTNAME` environment variable which would point to either the IP address of the machine, or the dns record.
