### ISSUE TITLE
Document the use of DISCOVERY_HOSTNAME environment variable

### ISSUE THREAD

**Issue by dashersw** [dashersw/cote#160]
Certain (most?) redis implementations require setting the hostname explicitly in order for successful connections. We normally achieve this by setting `DISCOVERY_HOSTNAME`, and we should probably add it to the README.

**Comment by orgalaf** [comment]
anyone working on this? i could probably help. just used it in a kubernetes deployment with redis.

**Comment by ramonvermeulen** [comment]
Would love to see docs about this, currently trying to get this working in a Kubernetes environment with redis.
