### ISSUE TITLE
Multiple cote.Requester instances

### ISSUE THREAD

**Issue by bogdyak** [dashersw/cote#164]
Running on ubuntu 16.04 localy
Node 10.15.0
Cote 0.19.1

#### app.js
```JavaScript
const a = new cote.Requester({name:"first hello", key:"first"})
const b = new cote.Requester({name:"second hello", key:"second"})
```
#### a-service.js
```JavaScript
const _a = new cote.Responder({name:"first res", key:"first"})
```

#### b-service.js
```JavaScript
const _b = new cote.Responder({name:"second res", key:"second"})
```

That configuration perfectly working on local machine

Then I am deploying to GCP

#### Machine1 (app.js) internal-ip: 10.10.1.1
```JavaScript
const a = new cote.Requester({name:"first hello", key:"first"}, {broadcast:"10.10.1.2"})
const b = new cote.Requester({name:"second hello", key:"second"}, {broadcast:"10.10.1.3"})
```
```Bash
Hello! I'm a-service requester#fa50d8ba-0dd1-47e4-816b-5367c1a0fa0e 
========================
Hello! I'm b-service requester#fa50d8ba-0dd1-47e4-816b-5367c1a0fa0e 
========================
```

#### Machine2 (a-service.js) internal-ip: 10.10.1.2
```JavaScript
const _a = new cote.Responder({name:"first res", key:"first"}, {broadcast:"10.10.1.1"})
```
```Bash
First res > service.online a-serivce requester #fa50d8ba-0dd1-47e4-816b-5367c1a0fa0e
```

#### Machine3 (b-service.js) internal-ip: 10.10.1.3
```JavaScript
const _b = new cote.Responder({name:"second res", key:"second"}, {broadcast:"10.10.1.1"})
```
```Bash
Second res > service.online b-serivce requester #fa50d8ba-0dd1-47e4-816b-5367c1a0fa0e
```
# Issue
* Services never talk between each other, `app.js` can't connect to services

# case 1
If change code to:
#### app.js
```JavaScript
const a = new cote.Requester({name:"first hello", key:"first"}, {broadcast:"10.10.1.2"})
// const b = new cote.Requester({name:"second hello", key:"second"}, {broadcast:"10.10.1.3"})
```

Other files without changes

#### Machine1 (app.js) internal-ip: 10.10.1.1
```Bash
First hello > service.online first res #a2d1ba59-a8f2-4b39-9d81-b0c8e4865c78 on 8000
```

#### Machine2 (a-service.js) internal-ip: 10.10.1.2
```Bash
First res > service.online a-serivce requester #fa50d8ba-0dd1-47e4-816b-5367c1a0fa0e
```

#### Machine3 (b-service.js) internal-ip: 10.10.1.3
```Bash
Second res > service.offline b-serivce requester #fa50d8ba-0dd1-47e4-816b-5367c1a0fa0e
```

Please help me solve that

Before that tried initiating `Requester` then `Publisher` in the same file, still same issue

# 04.23.2019 Update
1) I made all machines in the same zone (us-east)
2) Added timeout before creating the second requester
Now I have like this:
```JavaScript
const a = new cote.Requester({name:"first hello", key:"first"}, {broadcast:"10.10.1.2"})
let b = {}
setTimeout(() => {
    b = new cote.Requester({name:"second hello", key:"second"}, {broadcast:"10.10.1.3"})
}, 3000)
```

So now I have services connected over 3 different machines, check logs:
```Bash
First hello > service.online first res #a2d1ba59-a8f2-4b39-9d81-b0c8e4865c78 on 8000
Hello! I'm a-service requester#fa50d8ba-0dd1-47e4-816b-5367c1a0fa0e 
========================
```
3 seconds after ...
```Bash
Hello! I'm b-service requester#fa50d8ba-0dd1-47e4-816b-5367c1a0fa0e 
========================
First res > service.offline a-serivce requester #fa50d8ba-0dd1-47e4-816b-5367c1a0fa0e
```
It says offline, but `a-service` is actually working and answering, but `b-service` - not.
So I guess it overwriting connection to other services when trying to initiate 2 connections to 2 different services in the same process.

**Comment by drubin** [comment]
> Then I am deploying to GCP
GCP and AWS block any broadcast or multicast packets. You will need to use redis service Discovery

**Comment by bogdyak** [comment]
Hi @drubin
Thanks for your message
But then why it works if I comment out one Requester instance? 
Before that, I was trying to do [like that](38047889dea641442049245f85b122f3dbae274c76ea82a61aa56361c241622f)
But also not worked, until I comment publisher.

**Comment by bogdyak** [comment]
@dashersw @drubin Please check my latest update

**Comment by drubin** [comment]
`{broadcast:"10.10.1.2"}` You are using different broadcast IP's they technically should be the same. https://github.com/dashersw/cote#broadcast-address 

But again as I said before  broadcast is not supported on Google's VPC's

https://cloud.google.com/vpc/docs/vpc 
>VPC networks only support IPv4 unicast traffic. They do not support broadcast, multicast, or IPv6 traffic within the network: VMs in the VPC network can only send to IPv4 destinations and only receive traffic from IPv4 sources. It is possible to create an IPv6 address for a global load balancer, however. 

So sorry I can't help support you in your effort to try leverage broadcast/multicast with GCP.]

I would suggest you switch redis service discovery.

**Comment by bogdyak** [comment]
@drubin Thanks for message. 
Can you show your example of using redis for that? Because I am not sure how redis can help there...

**Comment by bogdyak** [comment]
@dashersw @drubin Alright, I solved that using Redis.
But not sure about the logic of address which I should put in
`COTE_DISCOVERY_REDIS_HOST=10.142.0.6`

Should I run `redis-server` on each Machine or only on 1.

Currently, I made it work like that
#### 1 machine: 10.142.0.2
COTE_DISCOVERY_REDIS_HOST=10.142.0.2 node server.js

#### 2 machine: 10.142.0.4
COTE_DISCOVERY_REDIS_HOST=10.142.0.2 node first-service.js

#### 3 machine: 10.142.0.6
COTE_DISCOVERY_REDIS_HOST=10.142.0.2 node second-service.js

Do I need to have `redis-server` on machine 2, and machine 3 ??
