### ISSUE TITLE
nodejs server using expressjs not run other api when use cotejs

### ISSUE THREAD

**Issue by Kmax4ever** [dashersw/cote#169]
i use cotejs to create 1 microserevice to readfile xslx, when it run, but when cote responder readfile, another api have to waiting for readfile done. what i can do to for responder readfile and in time i cant use another api.

**Comment by dashersw** [comment]
Are you using `fs.readFile` or are you using `fs.readFileSync`? Please share an example piece of code.

**Comment by Kmax4ever** [comment]
my requester use cotejs
![image](https://user-images.githubusercontent.com/38153452/58896055-6b925980-871f-11e9-84b9-6fddc44453b5.png)

my funtion importexcel use to return pathfile
![image](https://user-images.githubusercontent.com/38153452/58896156-a1374280-871f-11e9-9503-855bbc36ff5f.png)

my responder to readfile to pathfile 
![image](https://user-images.githubusercontent.com/38153452/58896242-cb890000-871f-11e9-9593-a427cfb6886d.png)

my problem is when i run this api  
![image](https://user-images.githubusercontent.com/38153452/58896346-01c67f80-8720-11e9-8278-bc799fff8e60.png)
i can't run other api, i hope it cant be run api  **/employee/import** , Excel reading can run in the background and i can run other api in that time

**Comment by dashersw** [comment]
As far as I can see, `readFile` is an async function, but you're only calling it non-blocking in `employeeResponder.on('importexcell'...`. Try `await readFile(req.pathFile)`.
