### ISSUE TITLE
Best Practice for providing HTTP access to service

### ISSUE THREAD

**Issue by robodude666** [dashersw/cote#174]
Hello,

I'm curious what is considered the best practice for exposing a cote service over http. Say, for example, you have a products service and you want to expose endpoints for basic get/list/create actions. The way I see it there are three options:

1) Start an http server inside of your service.
2) Create a separate project that acts as an http server and consumes your service via a `cote.Requester`.
3) Create an api gateway project that consumes all of the various services and provides access to them via various endpoints.

Thanks,
-robodude666

**Comment by dashersw** [comment]
Hello! All three are plausible depending on the complexity of your project. I generally tend to go with the second option.
