### ISSUE TITLE
Unit Testing / Mocking

### ISSUE THREAD

**Issue by robodude666** [dashersw/cote#175]
What sort of unit testing / mocking capabilities does cote have?

Does cote have the ability to mock responses? For example, if my service depended on another service could I inject a fake response into a Requester?

**Comment by cakuki** [comment]
For unit testing, `send` method can be overridden with a mock function, for passing in fixed data.

```js
const randomReq = require('./random-requester')

before(() => {
  randomReq.send = async() => 1
})

describe('random requester', function() {
  it('should return 1', async function() {
    assert(await randomReq.send('number'), 1)
  })
})
```

In a more complex setup, where a service layer, for example, used in front of cote requester, this would make it harder to mock the send method directly. But thankfully [`proxyquire`](https://github.com/thlorenz/proxyquire) package is really useful for mocking `send` method of the sub-dependency module, the requester.

```js
const proxyquire = require('proxyquire')

const randomService = proxyquire('../src/random-service', {
  './random-requester': {
    randomReq: {
      send: async({ type }) => {
        if (type === 'number') return 1
        if (type === 'letter') return 'a'
        throw new Error('any error')
      }
    }
  }
})
```
