### ISSUE TITLE
Critical issue: cote does not respond to sequential queries with delay

### ISSUE THREAD

**Issue by georgyfarniev** [dashersw/cote#178]
Hello. I ran into the following issue: when I send query to same responder with some delay (say, 2 second), only first query get response. Here is code:

```js
import cote from 'cote'

const delay = (msecs: number) => new Promise((resolve: () => void) => setTimeout(resolve, msecs))
const onResponse = (err: any, res: any) => {
  console.log('result:', res)
  console.log('error:', err)
}

const responder = new cote.Responder({ name: 'auth' })

responder.on('request', (req: any, cb: any) => {
  console.log('received request: ', req)
  cb(null, 'response')
})

async function main() {
  const requester = new cote.Requester({ name: 'req' })

  requester.send({ type: 'request', data: 'fooBar' }, onResponse)

  await delay(2000)
  requester.send({ type: 'request', data: 'fooBar' }, onResponse)

  await delay(2000)
  requester.send({ type: 'request', data: 'fooBar' }, onResponse)
}

main()
```

Only first query gets response using the code above.

OS: Windows 10
Node: v12.2.0
Cote:  0.20.0

I also tried to turn off windows firewall, no effect.

UPD1: I tried to launch time service example (from top of cote documentation), and if I launch time **client.js** repeatedly, I get answer only for first time after **time_service.js** start

UPD2: I noticed that example above will work if I will stop few other cote services. They have nothing common with example above, not a service name nor query type.

**Comment by otothea** [comment]
@georgyfarniev I have tried this code and it is working for me. My best guess is that you are running multiple apps with cote responders and those other responders are receiving your messages instead. If you are running cote in multiple apps you should use the `key` or the `environment` config option when creating requesters/responders to segment your cote communications

```
const responder = new cote.Responder({ name: 'auth', key: 'myApp' })
...
const requester = new cote.Requester({ name: 'req', key: 'myApp' })
```

Of course, you would need to make sure each app uses a different `key` (or the same key if you _want_ them to communicate)

http://cote.js.org/#keys
http://cote.js.org/#environments

**Comment by georgyfarniev** [comment]
@otothea I have other responders as well, but they answer different message. According to documentation, keys are just optimization, that’s why I omitted them. I will try assign key as you suggested tomorrow and let you know. Thanks a lot 🙏

**Comment by otothea** [comment]
@georgyfarniev cote does not take into account what events a responder listens to. If the responder does not listen to the event being sent then I believe it is silently ignored.

**Comment by georgyfarniev** [comment]
@otothea it really worked. The problem is that documentation doesn't clearly says about such behavior, and mention that keys are just for optimization purposes. I expected it to check which requests responder will respond instead. I think it should be fixed (in doc) to prevent such confusions.

Thanks a lot for your hint. Glad to use **cote** efficiently. Closing this one.

**Comment by dashersw** [comment]
I updated the README to reflect this nature.

**Comment by georgyfarniev** [comment]
@dashersw thanks a lot
