### ISSUE TITLE
message payload compression

### ISSUE THREAD

**Issue by gustavomassa** [dashersw/cote#179]
Hello,

Does cote do any type of compression before sending the data through the network?
Or the data is transferred as it is(raw)?

**Comment by dashersw** [comment]
No, cote doesn't do compression. The data is transferred as a binary buffer.

**Comment by gustavomassa** [comment]
Do you think is a good idea to compress the data before sending?
I have some requests that sends 500mb-1gb of data, maybe compressing the data before sending and then decompressing when receiving, would be faster to transport through network (less data) and would use less memory when receiving the data, but we have to count the time to compress/decompress the data.

My idea is to use nodejs zlib: [https://nodejs.org/api/zlib.html#zlib_zlib](https://nodejs.org/api/zlib.html#zlib_zlib)

Using gzip/deflate, giving a max time to compress the data, like 1 second and then forcing a flush.
I would like to have your opinion about when transferring big amount of data.

**Comment by dashersw** [comment]
I would say — don't do it over cote. cote is for fast, slim messaging, and is capable of 200k messages a second. It's not meant for large transfers. I'd recommend to use a shared network drive and just transfer the path over cote. Also — cote doesn't currently support binary transfers anyway.

**Comment by dreambit** [comment]
@dashersw 

> Also — cote doesn't currently support binary transfers anyway.

Do u mean that right now it is not possible to send image?
Right not if i send image as buffer over cote, transmitted traffic is 3 x received, responder loads 100kb image and sends it to requester and transmitted traffic is about 350kb.

**Comment by dashersw** [comment]
@dreambit you can base64 it, but i wouldn't recommend it. cote is for microservices messaging, and sending files generally isn't a great idea. I recommend using shared storage.
