### ISSUE TITLE
await client.send({ type: 'time' }) promise always rejects

### ISSUE THREAD

**Issue by gerkirill** [dashersw/cote#180]
If I use an async / await approach in the time-service client example - the promise always rejects. The error contains a proper response from the time-server though.

client.js example:
```
const cote = require('cote');
const client = new cote.Requester({ name: 'Client' });

(async() => {
  try {
    const time = await client.send({ type: 'time' });
    console.localStorage(time);
  } catch (e) {
    console.log('ERROR');
    console.error(e);
  }
})();
```
I believe that's because axon's `send()` method uses `callback(result)` convention, while requester.js expects `callback(err, result)` convention. 
Also, [the typings for cote](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cote/index.d.ts)  declare `send()` method as one expecting `callback(error, result)`. But it is not the case according to the docs anymore.

**Comment by dashersw** [comment]
If you're making use of promises (as in the case of async/await) and use callbacks in the responder, the first parameter should be the error. If you only use callbacks, there's no such convention. An easy way to fix this is to always use promises or always use callbacks.

The typings are not official, and done by the community. I'd love to have someone correct them.

**Comment by gerkirill** [comment]
Ok, thx. Now I see. That's not really clear from the docs, though.
