### ISSUE TITLE
How to make Transactional on Request call?

### ISSUE THREAD

**Issue by radiegtya** [dashersw/cote#185]
How to make Transactional on Request call? I mean when a request.send called (A), then call another request from different server (B). When B disconnect, then A will be failed. Or when A had been submitted, then B will be submitted too when server B is UP. 

for example when calling this code, and product service disconnect:
```javascript
orderService.on('store', async (req, cb) => {
    //create order, then update the product stock
    const order = new Order(req.body)
    order.save((err, order)=> {        
        productRequester.send({ type: 'update', _id: order.productId, body: {stock: 10} }, (data) => {
            cb(data)
        })
    })
})
```
the order still saved, but when product service up again, its not updated the stock

Thanks

**Comment by dashersw** [comment]
If product service went down _before_ you could send the `update`, the `productRequester` would wait for another product service to come online. However, cote doesn't have any other transactional capabilities, it would be up to the application developer to ensure the stability of a transaction.

**Comment by radiegtya** [comment]
but the issue is, when product service comes online, the update is not trigerred.

**Comment by dashersw** [comment]
It would be great if you could send an automated test to reproduce the issue with all the steps included.

**Comment by radiegtya** [comment]
Thank for the answer Dashersw. Anyways, firstly I will change my code with publisher on order created and subscriber on product to update stock. If I think the architecture already correct and it still not running well, I will tell u via reproduce step here.

**Comment by radiegtya** [comment]
Hi @dashersw 

I have inspected some behaviour using cote when doing Event Sourcing persistent for Transactional purpose and data consistency. I am trying to disconnect a related service, execute API, then reconnect that related service. Here are the behaviour I've Found (Note I am using Mongoose here):


## 1. Call another service, directly inside a service (NOT WORK)

product-service.js
```javascript
const cote = require('cote')({ redis: { host: 'localhost', port: "6379" } })
const productService = new cote.Responder({ 
    name: 'Product Service',
    key: 'product'
})

const Product = require('./Product') //I am using mongoose

productService.on('update', async (req, cb) => {
    Product.update(
        {_id: req._id},
        req.body        
    , cb)
})
```

order-service.js
```javascript
const cote = require('cote')({ redis: { host: 'localhost', port: "6379" } })
const orderService = new cote.Responder({ 
    name: 'Order Service',
    key: 'order'
})

const productRequester = new cote.Requester({ 
    name: 'Product Requester', 
    key: 'product',
    timeout: 1000,    
})

const Order = require('./Order')

orderService.on('store', (req, cb) => {
    //create order, then update the product stock
    const order = new Order(req.body)
    order.save((err, doc)=> {
        //ITS NOT EXECUTED WHEN SERVICE OFF, AND UP AGAIN
        productRequester.send({ type: 'update', _id: doc.productId, body: { $inc: { stock: 1 }} })                
   })
})
```

## 2. Publish 'onCreated' event, for other service doing something (NOT WORK)

order-service.js
```javascript
const cote = require('cote')({ redis: { host: 'localhost', port: "6379" } })
const orderService = new cote.Responder({ 
    name: 'Order Service',
    key: 'order'
})
const orderPublisher = new cote.Publisher({
    name: 'Order Publisher',
    // namespace: 'order',
    // key: 'order',
    broadcasts: ['orderCreated'],
})

const Order = require('./Order')

orderService.on('store', (req, cb) => {
    //create order, then update the product stock
    const order = new Order(req.body)
    order.save((err, doc)=> {
        //PUBLISH orderCreated
        orderPublisher.publish('orderCreated', doc.productId)
   })
})
```

product-service.js
```javascript
const cote = require('cote')({ redis: { host: 'localhost', port: "6379" } })
const productService = new cote.Responder({ 
    name: 'Product Service',
    key: 'product'
})
const orderSubscriber = new cote.Subscriber({
    name: 'Order Subscriber',
    subscribesTo: ['orderCreated'],
})
const productRequester = new cote.Requester({ 
    name: 'Product Requester', 
    key: 'product',
    timeout: 1000,    
})

const Product = require('./Product') //I am using mongoose

productService.on('update', async (req, cb) => {
    Product.update(
        {_id: req._id},
        req.body        
    , cb)
})

//THIS IS NOT WORKING TOO
orderSubscriber.on('orderCreated', (productId) => {
    productRequester.send({ type: 'update', _id: productId, body: {stock: 10} })
})
```

## 3. Call Requester on API Call (WORK)

product-service.js
```javascript
const cote = require('cote')({ redis: { host: 'localhost', port: "6379" } })
const productService = new cote.Responder({ 
    name: 'Product Service',
    key: 'product'
})

const Product = require('./Product') //I am using mongoose

productService.on('update', async (req, cb) => {
    Product.update(
        {_id: req._id},
        req.body        
    , cb)
})
```

order-service.js
```javascript
const cote = require('cote')({ redis: { host: 'localhost', port: "6379" } })
const orderService = new cote.Responder({ 
    name: 'Order Service',
    key: 'order'
})

const Order = require('./Order')

orderService.on('store', (req, cb) => {
    //create order, then update the product stock
    const order = new Order(req.body)
    order.save(cb)
})
```

api.js
```
const express = require('express')
const bodyParser = require('body-parser')
const cote = require('cote')({ redis: { host: 'localhost', port: "6379" } })
const productRequester = new cote.Requester({ 
    name: 'Product Requester', 
    key: 'product',
})
const orderRequester = new cote.Requester({ 
    name: 'Order Requester', 
    key: 'order',
})

const app = express()
app.use(bodyParser.json())

app.post('/order', (req, res)=>{
    //create the order
    orderRequester.send({ type: 'store', body: req.body }, (err, doc) => {
         res.send(doc)
         const productId = doc.productId
         productRequester.send({ type: 'update', _id: productId, body: { $inc: { stock: 1 }} })                
    })    
})

```

## Summary
Anyways it is already worked, but I am confuse why the first and the second solution did not work. Can You explain? Thank for the amazing package BTW! I think I'll use this with GraphQL and will be amazing!

**Comment by dashersw** [comment]
They would all work — the problem is the timeout. In the first two you have 1000ms timeout, which means unless the responder comes back online in a second, the message will be lost. Having said that, I wouldn’t recommend publish / subscribe pattern here (your 2nd option) as they use volatile messages. Unlike a requester, a publisher doesn’t queue updates if no subscribers are there.

**Comment by radiegtya** [comment]
Yeah, I removed the timeout (which I am forgot to remove) and it just work. Except the pubsub pattern as You said above. Thank for the good explanation :)
