### ISSUE TITLE
[Question] Where to find the key value store for Event Sourcing?

### ISSUE THREAD

**Issue by radiegtya** [dashersw/cote#186]
Where to find the key value store for Event Sourcing? I need to watch it to make my own monitoring tools and alert when a service is down, and how many time, and on what state. Thank

**Comment by dashersw** [comment]
There is no central key value store, but every service keeps their own (hence the mesh network). You can listen for `"cote:added"` and `"cote:removed"` events and get notified of service changes.

**Comment by radiegtya** [comment]
So how did cote knows what to do from queue, when service is down, and up again?

**Comment by dashersw** [comment]
Each requester has its own queue.

**Comment by radiegtya** [comment]
I see, then where the requester save the queue at? Can I look inside the queue?

**Comment by dashersw** [comment]
`requester.sock.queue` gives you the queue for each requester.

**Comment by radiegtya** [comment]
Thank @dashersw. Anyways I know that the queue is not persistence. When the requester server GOING DOWN, the queue get LOST. Is it not dangerous? Or how to enable cote queue to be persistence?

**Comment by dashersw** [comment]
cote is for microservices where you run multiple copies of each service. Ideally there are no services that have queues. For this reason, cote doesn't support persistence, because that's not a recommended way of implementing microservices.

**Comment by radiegtya** [comment]
Thank for the explanation. Then my next question is how to subscribe to `requester.sock.queue` when it is change?

**Comment by radiegtya** [comment]
anyways I already got the point, I'll close this for now. But it will be nice if we discuss furthermore here :)

**Comment by crapthings** [comment]
how to listen cote:added? @dashersw

**Comment by dashersw** [comment]
I believe you found it, @crapthings ?
