### ISSUE TITLE
How to connect my services through OpenVPN?

### ISSUE THREAD

**Issue by arvitaly** [dashersw/cote#195]
Hello! Thanks for great library!
I have the multiple network interfaces on the two machines. And i have a virtual network via OpenVPN (with addresses on every machine like 10.8.0.x). How should i to config my _cote_?

**Comment by dashersw** [comment]
You either need IP broadcast/multicast, or a central Redis instance on the same network.

**Comment by arvitaly** [comment]
Actually, it turned out not so easy, because in _tun_ mode OpenVPN creates an own network on every machine (a connection works through virtual tunnel). So, I don't know a method how to make it possible.

**Comment by dashersw** [comment]
If the machines are able to talk to each other, all they need is to talk to another Redis instance on the same network. then you configure IP addresses of each machine via environment variables.
