### ISSUE TITLE
How to run cote's services on EKS?

### ISSUE THREAD

**Issue by LypkoAlex** [dashersw/cote#196]
hi. I have developed services that communicate with each other by cote, but when I deployed it to the amazon eks they cant connect to each other. I have installed the wave-net plugin. What should I do? maybe I need to do some configurations etc

**Comment by itschrono** [comment]
Hey LypkoAlex, I think you should find the proper broadcast or multicast adresse (there is no multicast in cloud network like eks I think). So find out your private network IP range and use the broadcast adresse. You also need to create a private network and a connect your different instances in it.

**Comment by LypkoAlex** [comment]
I've resolved it. use Redis :)
