### ISSUE TITLE
Cote throws an error after the first request

### ISSUE THREAD

**Issue by kabhimanyu** [dashersw/cote#212]
Hi I have implemented and have been using cote for over a week now. After the first Call to the Requester , I just end up getting an error Saying "No Listener found for event: GET_USER"

But I have made sure both my requester and Responder are up and running. I have used cote in my other projects before as well, Have never come across this issue before. 

<img width="789" alt="Screenshot 2020-01-22 at 1 16 56 PM" src="https://user-images.githubusercontent.com/5457491/72875081-83a00300-3d19-11ea-9479-8db8b311e40f.png">
<img width="789" alt="Screenshot 2020-01-22 at 1 17 30 PM" src="https://user-images.githubusercontent.com/5457491/72875096-90bcf200-3d19-11ea-8a22-ea4ccb5e37e0.png">

**Comment by dashersw** [comment]
It's very probable that your different responders are lacking namespaces to differentiate them, and that's why GET_USER request ends up in PLAN RESPONDRER and other responders.
