### ISSUE TITLE
How to check master node?

### ISSUE THREAD

**Issue by tamtakoe** [dashersw/cote#219]
I see `isMaster` in initial event payload. So I assume that Cote based on Raft-like alghoritm and one node should be a lider. Does it possible to check `isMaster` status inside a node? It is really useful feature if I want to periodically grab data from the database on the master node and distribute it to the slaves nodes.

**Comment by dashersw** [comment]
cote is a true mesh network, in that there are no masters or slaves.

**Comment by tamtakoe** [comment]
Hmm... What `isMaster` does it mean?

**Comment by dashersw** [comment]
It is a residue of an underlying library, node-discover, which would be used for your purpose. You might want to look into node-discover for what you want.

**Comment by tamtakoe** [comment]
I will see, thanks for advice!
