### ISSUE TITLE
Project active and maintained?

### ISSUE THREAD

**Issue by crobinson42** [dashersw/cote#223]
Hello - I spent the evening reading through this project, amazing work!

I'm curious if this project is losing maintenance and future development from the authors/contributors. The reason I'm curious is because I'm searching for a solution(s) to replace ~20 individual Node.js micro-services and I think anyone would agree that they wouldn't want to invest time migrating/adopting to a new framework such as Cote only to find that it's no longer actively developed and maintained.

Just curious - thanks for the great project and documentation!

**Comment by dashersw** [comment]
Hi! Although we are not _very active_ in development of new features, the Slack community is alive and we look into every issue asap.
