### ISSUE TITLE
cote.js actively maintained?

### ISSUE THREAD

**Issue by loicnestler** [dashersw/cote#244]
Hey!

I just came across cote.js and were quite impressed by it's simplicity and developer experience.
I'm currently working on a big SaaS product and I think cote would be the ideal solution for my needs (I am currently doing inter-process communication via AMQP however I am not that pleased with it).

Is this library actively maintained? And if not, is it feature-complete?

Thanks in advance!

**Comment by dashersw** [comment]
Hello! Yes, I'm still dedicated to cote, and actively fix bugs — and I believe it provides a useful, battle-tested set of features.

**Comment by loicnestler** [comment]
I've played around quite a lot with it and I love it so far!
Thank you!
