### ISSUE TITLE
Support specific ip addresses of instances.

### ISSUE THREAD

**Issue by ulion** [dashersw/cote#252]
My env is in some cloud server env, lan addresses, 172.16.xx.xx, two servers, but neither broadcast nor multicast is supported since there are many servers in that LAN and broadcast/multicast are disabled in that case.

I need a fallback way without redis to just simply supply some ip addresses to let the instances to discover between each other. Isn't this the most simple fallback use case?

**Comment by dashersw** [comment]
You can definitely do it via environment variables! Just set `DISCOVERY_HOSTNAME` env var to the ip address :)

**Comment by dashersw** [comment]
If you are entirely sure about your machines and services, you can have a look at [axon](https://github.com/tj/axon), which is the library cote makes use of underneath.

**Comment by ulion** [comment]
So DISCOVERY_HOSTNAME does not work? as zero-conf, I would expect if every instance configured any ip/port pairs, then can exchange nodes info so get together as much as possible, so no need each instance configure all instances ip/ports. maybe just supply one share ip/port should also work for the worse case.

> ~You can definitely do it via environment variables! Just set `DISCOVERY_HOSTNAME` env var to the ip address :)~
> 
> cote works with an auto-discovery mechanism. Supplying some IP addresses is great, but how will the instances discover each other? For that you would need to supply all the IP addresses of all the services, and that doesn't work with the fundamentals of cote, as it's not 0 configuration and not auto-discovery, and not scalable.

**Comment by dashersw** [comment]
`DISCOVERY_HOSTNAME` works if you have redis or another discovery mechanism like weave net. You can't exchange these ip/port configurations without a centralized mechanism, whether it's the broadcast/multicast mechanism or redis. How will they "get together as much as possible"?

cote doesn't try to replicate an auto discovery mechanism in software. It expects you to have either weave net, a broadcast / multicast mechanism, or redis. It's possible to add further discovery tools like etcd or zookeeper, but one would need to build these integrations.

**Comment by ulion** [comment]
Well, cote do have broadcast and multicast as the basic discovery tool. what I really need is the other fallback way to specific other node ip/port to do the same work as broadcast or multicast in an env where broadcast and multicast do not work.
For my most simple case, 2 servers, but I found no simple way to connect them together with cote in such env.

**Comment by dashersw** [comment]
If you can't use redis or [weave net](https://www.weave.works/oss/net/), currently there are no other alternatives to replace broadcast or multicast with.

**Comment by ulion** [comment]
yep, that's what this issue for. for now, I have to switch to use moleculer since it supplied the fallback way for my case: https://moleculer.services/docs/0.14/networking.html

**Comment by dashersw** [comment]
IP addresses should be unknown and irrelevant in cloud apps. Cloud apps follow the cattle approach, whereas specific IP addresses mean you have pets. I recommend switching to cattle, and if that's not what you are after, cote definitely isn't the right tool. (more about [pets vs cattle](http://cloudscaling.com/blog/cloud-computing/the-history-of-pets-vs-cattle/)).

Cote won't support specific IP addresses, as it's counter to the cloud native approach of building scalable infrastructure.
