### ISSUE TITLE
Using cotejs on k3s cluster

### ISSUE THREAD

**Issue by alexander-hagen** [dashersw/cote#253]
I have several containers running on a k3s kubernetes cluster. This is a cluster if several raspberry pi's. Software under development is , running locally.

Discovery didn't work without redis, So I have set-up a redis server on the cluster with an IP address exposed outside of the cluster to allow discovery between containers in the cluster, and programs running locally. Now discovery works well, both for the containers, and for the local programs. They seem to use port 8000 and 8001.

When all programs are running locally, everything works fine. When running in the cluster, services are discovered correctly in each container, and locally, but messages send from requester to responder (and vice versa), or from publisher to subscriber, never arrive. Not between containers, not from container to local, and not from local to container.

I assumed that using redis would be sufficient, but apparantly it is not. I've exposed ports 8000-9000 when building the docker images, and have added ports 8000 and 8001 to the Kubernetes yaml files, but so far to no avail.

Is it still required to open ports when using redis? If not, I could use some suggestions on how to troubleshoot redis. If ports must be open, I could use some help on how to configure this on the k3s cluster. My cluster has metallb as a load balancer, and traefik for routing. I'd be happy to share my config files here.

I have tried  `const cote = require('cote')({ redis: { host: 'redis' }, hostname: localIP });`, with localIP being the cluster internal IP, the pod's external IP, assigned by metallb, and using hostname as servicename.namespacename.svc.cluster.local

**Comment by alexander-hagen** [comment]
I managed to get this working by using environment variables.

**Comment by VEROLAMAZ** [comment]
Hi @alexander-hagen, could you  share how you solved the issue? I am facing similar problems. Thanks!!
