### ISSUE TITLE
K3S Kubernetes Cluster: TypeError [ERR_INVALID_ARG_TYPE]: The "options.port" property must be one of type number or string. Received null

### ISSUE THREAD

**Issue by alexander-hagen** [dashersw/cote#254]
I'm running 6+ NodeJS programs, each with a combination of requesters, responders, publishers and subscribers. These programs are running on a k3s kubernetes cluster. I use redis for service discovery.

To make this work, I need to Expose ports when building the docker images. At the moment I expose ports 8000-9999 but with all programs running, I get:

TypeError [ERR_INVALID_ARG_TYPE]: The "options.port" property must be one of type number or string. Received null
    at new NodeError (node:internal/errors:329:5)
    at lookupAndConnect (node:net:989:13)
    at Socket.connect (node:net:968:5)
    at ReqSocket.Socket.connect (/usr/src/app/node_modules/@dashersw/axon/lib/sockets/sock.js:297:8)
    at Requester.onAdded (/usr/src/app/node_modules/cote/src/components/requester.js:94:19)
    at Discovery.<anonymous> (/usr/src/app/node_modules/cote/src/components/component.js:32:18)
    at Discovery.emit (node:events:381:22)
    at Network.Discover.self.evaluateHello (/usr/src/app/node_modules/@dashersw/node-discover/lib/discover.js:176:9)
    at Network.emit (node:events:369:20)
    at /usr/src/app/node_modules/@dashersw/node-discover/lib/network.js:72:22 {
  code: 'ERR_INVALID_ARG_TYPE'
}

This can happen to any pod in the cluster, so I guess it's related to port usage. Is it possible to assign specific ports to a requester, responder, etc, or is it possible to use redis for the communication, and not only for the discover?

**Comment by alexander-hagen** [comment]
The null value seems to come from axon:sock client. I also have this outside the cluster, so it's not related to k3s. Could this be redis related?

  axon:sock server accept 192.168.12.92:54157 +515ms
  axon:sock server add socket 0 +1ms
Requester User Configurations > service.online Responder to User Config Requests#00e80f63-a90d-4e8b-bd64-deb9f0e1e588
  axon:sock client connect attempt 0.0.0.0:null +1s
node:net:989
      throw new ERR_INVALID_ARG_TYPE('options.port',
      ^

**Comment by alexander-hagen** [comment]
I made some progress with debugging. The NodeJS programs that have this issue, both have this Requester that is causing the error:

const
  cote = require('cote')({ redis: { host: 'redis' } });
const configRequester = new cote.Requester({ name: 'Requester User Configurations', key: 'user.processor' });

The NodeJS that has the responder for this has the following:

const
  cote = require('cote')({ redis: { host: 'redis' } });
const configPublisher = new cote.Publisher({ name: 'Publisher to user configuration changes', key: 'user.publisher' });
const configResponder=new cote.Responder({ name: 'Responder to User Config Requests', key: 'user.processor' });

If I remove the Publisher, and only keep the Responder, then the issue is gone. What's wrong with the definition of the Publisher?

**Comment by VEROLAMAZ** [comment]
We experienced similar issues when we upgraded to Kubernetes v1.20.2 (provider: Digital Ocean) using cote v1.0.2.
We "fixed" it  by setting port manually because we detected that cote wasn't able to find a free port to use and was trying to set it to 65535.

Sample code:
`const responder = new cote.Responder({
  name: "TEST1",
  key: "TEST1",
  port: 8000,
});`

We couldnt find any other solution.

**Comment by gnanaprakash** [comment]
> We experienced similar issues when we upgraded to Kubernetes v1.20.2 (provider: Digital Ocean) using cote v1.0.2. We use cote with REDIS. We "fixed" it by setting port manually because we detected that cote wasn't able to find a free port to use and was trying to set it to 65535.
> 
> Sample code: `const responder = new cote.Responder({ name: "TEST1", key: "TEST1", port: 8000, });`
> 
> We couldn't find any other solution. I hope it helps.
> 
> We are facing now random timeout issues after upgrading to Kubernetes v1.20.9. ...

Thank you! This really helps.
