### ISSUE TITLE
Invalid 'main' field - node-discover

### ISSUE THREAD

**Issue by soloroman** [dashersw/cote#255]
Monitor tool logged this to console on only monitor instance running.

```
import cote from 'cote';
cote.MonitoringTool(3000);
```

`
DeprecationWarning: Invalid 'main' field in '..../node_modules/@dashersw/node-discover/package.json' of 'discover'. Please either fix that or report it to the module author
`

How could i help to solve this?

**Comment by aziznatour** [comment]
Any update on this? Issue occurs on Node v16.6.2 and cote v1.0.2

**Comment by dashersw** [comment]
This wasn't causing any issues, but, I just fixed it with cote@1.0.3!

Thanks for reporting!
