### ISSUE TITLE
Remove hiredis dependency

### ISSUE THREAD

**Issue by ziggi** [dashersw/cote#258]
Related to #256

`cote` depends on `@dashersw/node-discover^1.0.5`
`@dashersw/node-discover^1.0.5` depends on `redis^2.7.1"`
`redis^2.7.1"` depends on `redis-parser^2.6.0`
`redis-parser^2.6.0` depends on `hiredis^0.5.0`

So, It would be nice to bump `redis` version to 3.0.0+ where hiredis dependency was removed ([redis changelog](https://github.com/redis/node-redis/releases/tag/v3.0.0))

**Comment by dashersw** [comment]
Thank you @ziggi! I'll have a look at this over the weekend.

**Comment by mikey0000** [comment]
Update to use node-redis instead or add as peer dependency please.

**Comment by dashersw** [comment]
Moved to ioredis in version [v1.1.0](https://github.com/dashersw/cote/tree/v1.1.0)
