### ISSUE TITLE
Can't start cote due to port issue

### ISSUE THREAD

**Issue by tommyzat** [dashersw/cote#263]
Hello!

I'm getting this port error when starting cote:
`TypeError [ERR_INVALID_ARG_TYPE]: The "options.port" property must be one of type number or string. Received null`

I have specified a custom port.

**Comment by aziznatour** [comment]
Were you able to fix it? @tommyzat

**Comment by tommyzat** [comment]
> Were you able to fix it? @tommyzat 

Yes, not sure how I fixed it tho
