### ISSUE TITLE
Issue Installing Cote via NPM 

### ISSUE THREAD

**Issue by zdog1230** [dashersw/cote#29]
There's an issue involving the use of 'dashersw/axon' as it should be just 'axon'. If that can be fixed back that would be helpful as the old naming scheme isn't in npm.

--------

npm ERR! 404 'dashersw/axon' is not in the npm registry.

**Comment by dashersw** [comment]
@zdog1230 which version of Node and npm are you running?

I'm on node v6.3.0 and npm 3.10.3 and it installs fine.

**Comment by kevmt** [comment]
Hi @dashersw I am also having problem installing using the command:

`npm i cote`

I'm on on node v8.11.1 and npm 6.4.1
