### ISSUE TITLE
Function to return List of cote nodes

### ISSUE THREAD

**Issue by zdog1230** [dashersw/cote#30]
A feature to return the list of currently connected cote nodes would be great for applications. Especially mine with hotswapping nodes.

**Comment by dashersw** [comment]
@zdog1230 have you checked the monitor component? In addition to the monitor, albeit undocumented, each node gives you the list of all the discovered nodes.

**Comment by zdog1230** [comment]
Thanks for the reply! Do you know where in the library does the node return that list that I can call?

**Comment by dashersw** [comment]
Given a cote component like the following;

```js
var requester = new Requester({
    name: 'requester',
    requests: ['request']
});
```

the nodes it discovers are accessible via `requester.discovery.nodes`.
