### ISSUE TITLE
Not working on CentOS 7

### ISSUE THREAD

**Issue by RobertSmart** [dashersw/cote#31]
Hi,

I've just created two new services based on the sample code on the website and it just doesn't work. I've tried running as separate processes on the same machine and on two separate VM's on the same network. I've opened the ports on iptables and turned off the firewall, but still no joy.

The fact that it doesn't even work on the same machine tells me something is up.

It works fine on a single instance of unbuntu. What is different with CentOS?? Any ideas?

**Comment by dashersw** [comment]
Very interesting! I had it running on CentOS 7 before, but that was a while ago. I will have a look at it in the morning. Meanwhile, you could try to see if your network interface has broadcast enabled. Cote also supports multicast, so you could try to use multicast addresses.

**Comment by RobertSmart** [comment]
How do i check if broadcast is enabled? Another thing i noticed is that on unbuntu, the console output shows that the sockets connect. But on centos this never shows, even though the timer emits the events. So could the process be getting stopped from opening a socket or something? I've also passed a port number into the options for a port i know is open. But again this doesn't explain why it doesn't work on the same machine.

**Comment by dashersw** [comment]
The best way for finding out if broadcast is supported is to contact the cloud provider. Are you using AWS, DigitalOcean or alike? Most cloud providers don't support IP broadcast or multicast out of the box. That's why I would recommend using either Docker, or going with bare metal servers that you own/manage.

Having said that, I have tried tunning "responder" and "requester" in the examples folder in single machines with CentOS 7.2 in AWS, DigitalOcean and Scaleway. They all work, given that they are in a single machine. I also tried multi machine and IP broadcast and multicast, but none of them works.

Deploying microservices in Docker containers with Docker Swarm, Docker Cloud or Kubernetes gives you an overlay network where broadcast and multicast both work. That is the best way to achieve multi-host networking in cote.

**Comment by RobertSmart** [comment]
This is running on a vm hosted in vmware pro on my machine. The two seperate vms are running in host only network, and i can ping between them. It needs to be installed in a provider that does not support docker, so can't use that. I actually couldn't get native axon working either, if thats any clue

**Comment by dashersw** [comment]
That is weird. I have used cote with VMWare before; although I haven't set it up. Axon, on the other hand, doesn't depend on broadcast, but regular TCP socket connections. Axon not working is very weird.

**Comment by mertcetin** [comment]
I tried to reproduce the issue with two guest Oracle Linux 6.7 machines on a VMWare host. I ran the examples provided within cote and they worked without a hitch. I don't have VMWare on my local computer but will try to provision two centos7 machines on virtualbox platform. I'll share the details.

**Comment by mertcetin** [comment]
BTW, first thing that comes to mind while thinking about the differences between ubuntu and centos is SELinux. I don't know whether it directly affects axon TCP communication or not but I guess it's worth a try. Could you please check your SELinux status with `getenforce` command? If it is enabled could you please disable it in /etc/selinux/config by setting SELINUX=disabled and reboot.

**Comment by RobertSmart** [comment]
Hi,

Thanks for the reply.

How do i check if broadcast is enabled? And why would this effect both processes running on the same machine? I'm running these vm's on vmware pro with the network adapter set to host-only.

Sent from my iPad

On 21 Oct 2016, at 21:38, Armagan Amcalar <notifications@github.com<mailto:notifications@github.com>> wrote:


Very interesting! I had it running on CentOS 7 before, but that was a while ago. I will have a look at it in the morning. Meanwhile, you could try to see if your network interface has broadcast enabled. Cote also supports multicast, so you could try to use multicast addresses.

-
