### ISSUE TITLE
Simple environment test

### ISSUE THREAD

**Issue by ChrisCinelli** [dashersw/cote#38]
This seems pretty interesting but it also looks like in order to give it a spin will take a no trivial effort.
It would be nice to see a script that pull up a few services. 

Maybe you can use a `docker-compose` file that can spin up a few docker containers with the services running inside. 

It would be also nice to see the output of the monitoring tool.

**Comment by dashersw** [comment]
Have you checked the extensive example at https://github.com/dashersw/cote-workshop ? It has both docker-compose and Docker Cloud configurations together with the monitoring tool. How shall we integrate it further? Would it be better to add example Docker configurations to the readme?

**Comment by ChrisCinelli** [comment]
Nope... Thank you to point it out. I will take a look.
I think a link at the beginning on the README would be useful

**Comment by dashersw** [comment]
It was already in the readme but I made sure it's more exposed. Thank you!
