### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by ChrisCinelli** [dashersw/cote#39]
Does it have tests?

**Comment by dashersw** [comment]
Currently there are a small number of tests for the `es6` branch, which is a modernization/rewrite of all components. While the branch is a drop-in replacement for `master`, I haven't added them to `master` yet. Having said that, the underlying libraries used for trsnsport are heavily tested in their own scope.

**Comment by ChrisCinelli** [comment]
Thanks. I think a `/tests` folder in the repo could add some confidence in `cote`.

**Comment by dashersw** [comment]
cote now has 97% code coverage — since ES6 rewrite.
