### ISSUE TITLE
Cote.js (promise) in Express 

### ISSUE THREAD

**Issue by Keramet** [dashersw/cote#51]
Hi!
I'm trying to use cote.js in my express app.
Here my route code:

```
...
router.get('uuid', (req, res, next) => mainSvc.getUuid()
        .then( data => res.json(data) )
        .catch( next )
);
```

Here mainSvc code:

```
const      cote = require('cote'),
  uuidRequester = new cote.Requester({ name: 'uuid requester' });

module.exports = {
...
  getUuid:  ()=> {
       const  request = { type: 'uuid' };
        
       return  uuidRequester.send( request )
            .then( data  => {
                console.log('Data:', data);
                return  data;
            })
            .catch( err => {
                console.error('Error:',  err);
                return  Promise.reject( err );
            })
       ;
  }
...
};
```
Here my service to generate uuid:
```
const   uuid = require('uuid/v4'),
        cote = require('cote'),
   responder = new cote.Responder({ name: 'uuid responder' });

responder.on('uuid', (res, cb) => {
    cb({ uuid: uuid() });
});
```

And in console I got error:

> uuid requester > service.online uuid responder#47cdd6ce-ccfb-4043-bcf7-e01b54b1b626 on 8000
> Error: { uuid: 'e917380b-8128-4bd7-b087-3ed136987289' }

[Error](http://joxi.ru/Q2KGMVNT9bk3w2)

What I did wrong and why I got Error instead Data?
Thanks

**Comment by Robophil** [comment]
@Keramet  i don't think you're returning a promise. In your **requester**, you seem to be expecting one. Try this
``` javascript
   const cote = require('cote'), uuid = require('uuid/v4'),
              responder = new cote.Responder({name: 'uuid Responder'}),
            
   responder.on('uuid', (req) => new Promise( (resolve, reject) => resolve(uuid()) )
```

**Comment by dashersw** [comment]
@Keramet hello! Actually, it's pretty simple. If you are using promises and callbacks together, you should make sure the first argument in the callback is the error object and it will be passed onto the `catch` handler, and the second argument is the actual result.

In your case, a simple `cb(null, { uuid: uuid() });` would work. On the other hand, you can also use `responder.on('uuid', (res) => Promise.resolve({ uuid: uuid() }))`.

**Comment by Robophil** [comment]
@dashersw I think this should be highlighted more in the readme  :-)

**Comment by dashersw** [comment]
I agree :)

**Comment by Keramet** [comment]
Thanks, guys!
