### ISSUE TITLE
Missing requests sending by cote.Requester

### ISSUE THREAD

**Issue by mrodessit** [dashersw/cote#52]
I have Requester that sends many requests (for example over some interval).
I want to make Responder that initiliaze then answer one request and die. I did it in several ways, but always when i start next Responder i miss some of requests.

What proper way to do that?

**Comment by dashersw** [comment]
Do you have example code? Normally cote doesn’t lose requests, unless you close a Responder while it should be processing some requests.

The ideal implementation is long-lived Responders. Killing Responders after each request is both against cote’s and Node.js’s philosophies.

However, if you must kill and restart Responders, you should implement a graceful exit. Whenever your Responder process receives a kill signal, it should first finish however much requests it has, and then call “responder.close()”. You can only quit once you don’t have any more messages, and the requester understands that the responder is no longer there.

Again, this is discouraged.
