### ISSUE TITLE
Communicate with python service

### ISSUE THREAD

**Issue by shyamchandranmec** [dashersw/cote#54]
Hi,
  Thanks for this library!!. This library really simplifies many things. 
I was wondering if this has a python lib. I have some node-js apps and some python apps. If there is no python lib available, what is the best way to communicate between these two apps? Redis? NATS? GRPC? PUB-SUB?

**Comment by dashersw** [comment]
Hello! Unfortunately, cote has no corresponding libraries in other languages. Although the protocol is fairly simple, the business logic behind it would still take time to implement. Redis would be a fairly simple solution for your needs.

**Comment by shyamchandranmec** [comment]
Cool. May be you can add this as an enhancement..

**Comment by dashersw** [comment]
Closing this in favor of #50.
