### ISSUE TITLE
Enable plugin support for service discovery

### ISSUE THREAD

**Issue by dashersw** [dashersw/cote#55]
Until Kubernetes and Docker Swarm get native support for IP broadcast/multicast, it makes sense to enable service discovery over another tool.

This is fundamentally at odds with cote's zero configuration approach; but in order to enable cote on limited environment such as public clouds, it's viable to introduce an optional alternative. This will also lead to greater adoption of cote.

**Comment by robodude666** [comment]
Would this be something worth reconsidering? Cote's zero-configuration capabilities are amazing. However, `consul` is a fairly popular service discovery system. Especially in the docker world. Combining `cote` with [`piloted`](https://www.npmjs.com/package/piloted)+[`containerpilot`](https://www.joyent.com/containerpilot) would make for some very fault tolerant applications.

Having cote support a plug-able service discovery system would allow users to reuse existing service discovery methods. This may also help cut down on the chatty-ness of cote.
