### ISSUE TITLE
Cote Just Doesn't Work

### ISSUE THREAD

**Issue by iwanjunaid** [dashersw/cote#56]
I try cote for the first time. I already run the time-service.js and client.js also with the monitoring tool. But nothing happened. Do i miss something?

**Comment by Robophil** [comment]
@iwanjunaid "**just doesn't work**" is a bit too broad don't you think?
Can you share your code so we can see what you're doing?
see https://github.com/dashersw/cote-workshop for a sample work. Hope this helps

**Comment by iwanjunaid** [comment]
sorry for the missing details. Here is the code:

time-service.js
```javascript
const cote = require('cote');
const timeService = new cote.Responder({name: 'Time Service'});

timeService.on('time', (req, cb) => {
  cb(new Date());
});
```
client.js

```javascript
const cote = require('cote');
const client = new cote.Requester({name: 'Client'});

client.send({type: 'time'}, (time) => {
  console.log(time);
});
```

**Comment by Robophil** [comment]
hi @iwanjunaid ,
The sample code above works. Just make sure you run the `time-service.js` first before running the `client.js` so by that time, the timeservice would be available
or better yet, replace your `client.js` code with 

```javascript
const cote = require('cote');
const client = new cote.Requester({name: 'Client'});

setInterval(()=>{
   client.send({type: 'time'}, (time) => {
  console.log(time);
})
}, 1000)
```

**Comment by dashersw** [comment]
In fact, you don't even need to care about the order of execution. The Requesters queue queries until a Responder is active — so you can run the client first and then the service, it will work.

@iwanjunaid this code works. could you tell us a bit more about your environment?

**Comment by iwanjunaid** [comment]
@dashersw Ubuntu 16.04, node v6.10.1 and cote 0.15.1.

**Comment by iwanjunaid** [comment]
Here is what i got after run node time-service.js

```bash
Hello! I'm Time Service#b53a3d5d-91d8-417a-9d12-189ccdf70a97 on 8000
========================
```

and here is the ouput for client.js

```bash
Hello! I'm Client#1dbb4524-39bc-4696-b0b2-588826db86dc
========================
```

**Comment by dashersw** [comment]
Are you running in the cloud, on your local machine or a virtual machine? Are you using Docker, multiple machines, etc?

**Comment by iwanjunaid** [comment]
@dashersw no, it is just a local machine on my laptop.

**Comment by iwanjunaid** [comment]
Is there a way to run cote verbosely ?

**Comment by dashersw** [comment]
Looks like IP broadcast doesn’t work on your machine. You could try setting it up, or you could fall back to multicast, or even redis — see the readme for that.

For debugging, there’s an environment variable DEBUG that you can use, setting it to * will give everything.

**Comment by iwanjunaid** [comment]
I try explicitly set the broadcast IP address and now it works! @dashersw thanks a million

**Comment by arefaslani** [comment]
@dashersw If IP broadcast doesn't work on my machine (with macOS Mojave), how to make it work?

**Comment by dashersw** [comment]
@arefaslani you can try the redis fallback.

**Comment by matejthetree** [comment]
I have Mac Mojave and everything works. Can you show code example?

**Comment by arefaslani** [comment]
@matejthetree  This is the responder:
```javascript
// server.js
const cote = require('cote');

const responder = new cote.Responder({ name: 'currency conversion responder' });

const rates = { usd_eur: 0.91, eur_usd: 1.10 };

responder.on("convert", req => req.amount * rates[`${req.from}_${req.to}`]);
```
and this is the requester:
```javascript
// client.js
const cote = require('cote');

const requester = new cote.Requester({ name: 'currency conversion requester' });

const request = { type: 'convert', from: 'usd', to: 'eur' };

setInterval(
  async () => {
    const amount = Math.ceil(Math.random() * 100);
    const res = await requester.send({ ...request, amount });
    console.log(`result: ${res}`);
  }, 2000
)
```

When I run both client and server, services can't find each other by default:
<img width="1280" alt="screen shot 1397-09-13 at 07 36 47" src="https://user-images.githubusercontent.com/1573492/49418573-1e492580-f798-11e8-99c4-0bf2cb3e79f0.png">

But when I use Redis fallback they will find each other but nothing happens:
<img width="1280" alt="screen shot 1397-09-13 at 09 15 20" src="https://user-images.githubusercontent.com/1573492/49421454-370c0800-f7a5-11e8-8a00-5a7cfa9095cf.png">

After using Redis fallback once, although without Redis, they will find each other sometimes but still nothing happens:
<img width="1280" alt="screen shot 1397-09-13 at 09 17 13" src="https://user-images.githubusercontent.com/1573492/49421497-6e7ab480-f7a5-11e8-8368-1172bdab3d25.png">

And in the end, when I return a Promise in the responder, everything works and I don't know why!
```javascript
const cote = require('cote');

const responder = new cote.Responder({ name: 'currency conversion responder' });

const rates = { usd_eur: 0.91, eur_usd: 1.10 };

responder.on(
  "convert",
  req =>
    new Promise(
      (resolve, reject) => resolve(req.amount * rates[`${req.from}_${req.to}`])
    )
);
```

<img width="1280" alt="screen shot 1397-09-13 at 09 19 24" src="https://user-images.githubusercontent.com/1573492/49421569-bbf72180-f7a5-11e8-9548-b5d939dd2eff.png">

I'm totally confused!

**Comment by dashersw** [comment]
you are right, actually you found the issue yourself. you can't return simple values in cote, they have to be promises. 

```js
responder.on("convert", req => req.amount * rates[`${req.from}_${req.to}`]);
``` 

will not work, it needs to be 

```js
responder.on("convert", req => Promise.resolve(req.amount * rates[`${req.from}_${req.to}`]));
```

**Comment by matejthetree** [comment]
Just make your respond function async so it returns promise by default or
use callback if you want to avoid that. But then you need to use callback
style in both requester and responder.

**Comment by arefaslani** [comment]
@dashersw and @matejthetree thank you for quick response and sorry for late reply! Yesterday I was all day to what goes wrong. I've created a simple problem that looks like the original one. Suppose we have three services:

* age responder: gets year of birth as integer and calculates the age
* greeter: gets the age from age responder and listens to greet event to return a greeting message
* greeter client: sends a name to the greeter service to show the greeting message

```javascript
// age responder service
import { Responder } from "cote";

const ageResponder = new Responder({ name: "age responder" });

ageResponder.on("calculate age", req =>
  Promise.resolve(new Date().getFullYear() - req.yearOfBirth)
);
```
```javascript
// greeter service
import { Requester, Responder } from "cote";

const ageRequester = new Requester({ name: "age requester" });
const responder = new Responder({ name: "greeter" });

(async () => {
  const age = await ageRequester.send({
    type: "calculate age",
    yearOfBirth: 1989
  });

  responder.on("greet", req =>
    Promise.resolve(`Hello ${req.name}! Your age is ${age} years.`)
  );
})();
```
```javascript
// greeter client service
import { Requester } from "cote";

const requester = new Requester({ name: "greet requester" });

(async () => {
  const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
  do {
    const res = await requester.send({ type: "greet", name: "Aref" });
    console.log(res);
    await delay(2000);
  } while (true);
})();
```

then I run all three services, each with a command like `COTE_DISCOVERY_REDIS=true npx babel-node service-file-name.js` and then services find each other but they didn't log anything! What is the problem here? How can I create a service that is at the same time a requester and a responder?

**Comment by dashersw** [comment]
you can read more about this here: https://github.com/dashersw/cote#keys

basically, if you don't have keys for your requesters / responders, all your responders should be able to respond to the same messages. you can't have `greet` and `calculate age` messages in separate responders. if that would be the case, you should segregate these services.

**Comment by dashersw** [comment]
> Note: By default, every Requester will connect to every Responder it discovers, regardless of the request type. This means, every Responder should respond to the exact same set of requests, because Requesters will load-balance requests between all connected Responders regardless of their capabilities, i.e, whether or not they can handle a given request.

If you have multiple Responders with varying response handlers, you will experience lost requests. In cote, this separation between responsibilities is called segmentation, or partitioning. If you wish to segment your requests in groups, you can use keys. Check out keys for a detailed guide on how and when to use segmentation.

**Comment by arefaslani** [comment]
@dashersw Thank you! I'll notify you about the result.

**Comment by SHAPPY0** [comment]
> I try explicitly set the broadcast IP address and now it works! @dashersw thanks a million

hey,
can you please share the code?
