### ISSUE TITLE
Architecture advice

### ISSUE THREAD

**Issue by FPierre** [dashersw/cote#57]
Hi there!

I currently works on a [CRM project](http://github.com/FPierre) (side project)
There is 1 **front app** (Vue.js), which calls 1 **HTTP API** (Express). This API calls **Services** (cote.js) and render results to the front app.

Is it better to have an API between front app and Services, or use Sockend possibilities (remove the API and call Services directly from front app)? API is usefull for authentication, but add a HTTP call layer

**Comment by dashersw** [comment]
I have incorporated authentication into Sockend, with standard socket.io auth mechanisms; therefore I use Sockend directly, and eliminating one layer (express) is also one less worry. But both approaches work equally good.

**Comment by FPierre** [comment]
I'll try to remove the API
