### ISSUE TITLE
Transfer big files (10MB)

### ISSUE THREAD

**Issue by Keramet** [dashersw/cote#59]
Hello.
How can I transfer ZIP file (10MB) from Requester to Responder? Is Cote allows to do this?
Thanks.

**Comment by Keramet** [comment]
How about file with size 10MB?

**Comment by DeadcatDev** [comment]
Same question, does it fit for big files?

**Comment by dashersw** [comment]
cote doesn't currently allow transfer of binary files in a coherent way. It's not very easy to implement it, but still doable. I would love to have some help from the community here.
