### ISSUE TITLE
Express API plus CoteJS standalone services sample

### ISSUE THREAD

**Issue by danihenrique** [dashersw/cote#60]
Hello,

Is possible to create Express Docker Containers, exposing an API Restful that responds to
CoteJS services, but those services are in anothers Docker containers?

If I use locally, run express at 3000 port, and them run cotejs services, it works.
Expresss routes send to cotejs that responds automatically.

But and I tried use those projects using Docker as I said above, the Express router doesnt "find"
the CoteJS that are running in another Docker container.

Can you explain me for how can I make it work?

Thanks ;)

**Comment by LucasBadico** [comment]
Why closed this?

**Comment by dashersw** [comment]
@LucasBadico if you have a specific question, you can open a new issue and we can cover it there.
