### ISSUE TITLE
Discussion: Failure handling and Circuit Breaker-ish behavior

### ISSUE THREAD

**Issue by maslennikov** [dashersw/cote#61]
Hi Armagan, this is not an issue, just an invitation to discuss your vision on the subject.

First of all, I want to thank your for a great project, looks very sleak, I am definitely giving it a try.

As I brushed through your repo, I noticed that you have patched the Axon library to queue up (indefinitely) the outstanding requests until the connection is up. Although viable for some use-cases, this decision looks very opinionated, hence my friendly inquiry.

Do you have any plans for advancing the mechanism with configurable failover behavior? Think response timeouts, limiting the queue length, defaults for failed requests, or may be even some state machinery like in circuit breaker.

Could you share your general opinion on this topic?

Thank you!

**Comment by dashersw** [comment]
Hello Alexey, thanks a lot for the input! You are actually right, it's quite opinionated to cover a large percentage of use-cases. All the alternatives you pointed out, timeouts and more, are actually features that I would love to have. It's just a matter of time investment, and in fact in the professional contexts I use cote, I implement at least a timeout on top.

So this would be a welcome addition to cote, should someone want to work/collaborate on it.

**Comment by maslennikov** [comment]
Thanks for a quick response! Love to hear that. Abstractions in cote look neat, so these things can be integrated very smoothly. I will start my small greenfield e-comm project with it and hope to be able to contribute!

**Comment by TomKaltz** [comment]
If I implement a timeout for my request how would I delete the request from the queue upon timeout?

**Comment by dashersw** [comment]
`requester.sock.queue` gives you an array of pending requests and their callbacks.

**Comment by robodude666** [comment]
@dashersw Have your thoughts changed since your first comment on this issue? It looks like timeouts were added via #125.

I feel having circuit breaker support would be a huge plus. Instead of a service sitting until the timeout waiting for a response the circuit breakers could be used to fail fast.

**Comment by dashersw** [comment]
@robodude666 I am still open to contributions, as part of new issues / PR’s. However, getting an actual circuit breaker that is general purpose is really hard to achieve.
