### ISSUE TITLE
Send a request to a node

### ISSUE THREAD

**Issue by francescoagati** [dashersw/cote#62]
Hi, is possibile send a request to a specific node?

**Comment by dashersw** [comment]
Hello, you have to give the requester and a responder a specific key, so that they will only connect to each other. However, this is discouraged.

**Comment by francescoagati** [comment]
What i want is more send a request to alla nodes and collect the respinse.
I cant use the nodes list in monitoring for send a request to all the nodes?

**Comment by dashersw** [comment]
But this is already how it works? Create one requester and as many responders as you like on any machine and it will work.

**Comment by francescoagati** [comment]
Yes but i need to send to a specific node

**Comment by dashersw** [comment]
Sorry, I'm not quite following. Maybe it would help if you could give me a more concrete example. The requests are load balanced in a round-robin way, so there is no way to influence where they end up. The only way to do it to create special keys, to be shared with a single responder and several requesters.

**Comment by francescoagati** [comment]
I have 5 nodes. And any node responds with a different value. What i need is calling all 5 nodes in parallel to capture the 5 differents value but without using publish/subscribe. Is a multi parallel   request/reply to all nodes that expose the same  service but any node return a differenti value (forma example the free memory)

**Comment by dashersw** [comment]
I see. There's no direct way to choose the server you'll send to. Although it's quite tricky, it still can be hacked, though. On the other hand, a quicker hack would be to get the number of connected nodes from the discovery property (requester.discovery.nodes), see which ones you are connected to, and then do the request that many times, so every node will reply at least once. Then save the responses with a unique key from each responder, so you know who they belong to.

**Comment by francescoagati** [comment]
Yes this can work thanks. But pub sub can work better
