### ISSUE TITLE
CoteJs Protocol & Integration with Express 

### ISSUE THREAD

**Issue by alaboudi** [dashersw/cote#63]
@dashersw This is somewhat a two part question:

1. The documentation lists out which protocols are not used but does not really state what protocol is used in cotejs. It sort of implies that it is a custom light weight protocol. Is that true? If that is the case, how do I go about testing my work independently on a request/response level without necessarily having to setup another service to test my work? 

 2. I have seen the express JS library example from a request stand point. That example makes a good API gateway example. But how would you incorporate the `Responder` to `expressJs`?

**Comment by dashersw** [comment]
Hello,

1) cote uses the [tj/axon](https://github.com/tj/axon) library underneath, and it uses a custom, very light weight protocol. The best way to test your service is to create another service as you said. But this should be no problem, because cote is already well-tested.
2) I am not sure I understand how you would like to incorporate a responder with express. Could you give me an example?

**Comment by sdeceuninck** [comment]
Hello,

I don't know exactly what you meant about the express integration, what I didn't is that, on all routes, I create a context representing the request and I pass the context to the cote service that can analyse to give an anwser. Something like that :
```
router.use(async (req, res, next) => {
   try {
      //Create context
      let context = {
         url: req.url,
         path: req.path,
         baseUrl: req.baseUrl,
         body: req.body,
         method: req.method,
         query: req.query
      }

      // Passing the context to the cote service
      let result = await services.ApiRequest(context);
      // The answer of the cote service is the result of the API
      res.status(200).send(result);
   }
   catch (e) {
      // catching errors send a 500 (internal server error)
      res.status(500).send({ error: e.message });
   }
})
```
The cote service just parse the URL, the method, the body to get the answer.

Hope it helps.
