### ISSUE TITLE
Rejecting promises

### ISSUE THREAD

**Issue by simonschllng** [dashersw/cote#64]
I am getting empty error messages from the Requester:

**responder**

````
authService.on('getAdminToken', req => {
  console.log('getAdminToken');
  const adminToken = {
    role: 'admin'
  };
  const options = {
    audience: 'http://domain.com/audience',
    expiresIn: '6 month'
  }
  return new Promise((resolve, reject) => {
    const jwt = sign(adminToken, config.jwtSecret, options);
    if(!jwt) reject(new Error('failed to sign token'));
    resolve(jwt);
  });
});
````

**requester**
````
requester.send({ type: 'getAdminToken' })
  .then((token) => {
    winston.info(token);
  })
  .catch(e => winston.error(e));
````

**output**
````
{
  "level": "error",
  "message": ""
}
````

I can't see the problem. What did I get wrong with cote?

It also sends the empty message when I do:

````

authService.on('getAdminToken', req => {
  return new Promise((resolve, reject) => {
    reject(new Error('test error message'));
  });
});
````

**Comment by simonschllng** [comment]
I found the source of the error but I do not know why the error is not logged correctly.

**Comment by dashersw** [comment]
I think it is because the `Error` object doesn't give the message when you `JSON.stringify` it.

This answer on StackOverflow might help: https://stackoverflow.com/a/18391400

**Comment by simonschllng** [comment]
Ok, understood. But what is the concept for cote regarding this. Shouldn't the cote add that function to the prototype?

**Comment by dashersw** [comment]
No, cote doesn’t enforce any decision on your objects and your style. It just turns whatever you give to it into JSON, and it’s the user’s responsibility to make sure any object passed in can be serialized into JSON. cote is a tool with which you can implement any structure you wish, and in my projects in production, I use a custom Error JSON serializer for this.

**Comment by Robophil** [comment]
This seems much easier
```javascript
JSON.stringify(err, Object.getOwnPropertyNames(err))
```
