### ISSUE TITLE
Multiple calls with same Requester

### ISSUE THREAD

**Issue by jlsan92** [dashersw/cote#73]
Hi, I'm instantiating a cote Requester and I try to use it multiple times (pointing to the same Responder in another process), but only the first Request is getting a response, the following ones don't. What could be happening ? Thanks!

**Comment by dashersw** [comment]
@jlsan92 could you share example code with us? Do you have more than one type of responders, for example, with varying event handlers?

**Comment by jlsan92** [comment]
My config is something like this:

1 Requester calling different functions on Responder

```javascript
// app1.js
const { Requester } = require('cote');

const requester = new Requester({
      name: 'Requester',
});
...
requester.send({ type, data }, res => console.log(res));
```

```javascript
// app2.js
const { Responder } = require('cote');

const responder = new Responder({
      name: 'Responder',
});

responder.on('functionlOne', ({ data }), cb => {
  // do something
  return cb();
});

responder.on('functionTwo', ({ data }), cb => {
  // do something
  return cb();
});

responder.on('functionThree', ({ data }), cb => {
  // do something
  return cb();
});
```

Only one "function" gets called, others never are executed. 

I'm trying this on Docker, already tried Redis backend and still no luck.

**Comment by dashersw** [comment]
@jlsan92 it looks like it should work, except for the handler syntax, which is more like `'event', ({ data }, cb) => { })`.

It doesn't have anything to do with redis — if one works, the others should also work. Make sure you don't have other responders running on your machine at the same time, that have different message names than what are listed here.

If you can share a more realistic example that demonstrates the issue, I can also help debug it.

**Comment by MaxSvargal** [comment]
I'm also have the same problem. The only first response of requests received.
First service is responder of get-methods of redis
Second service is responder of set-methods of redis
Third service request get method, modified data and request to save to second service.
But only first call receive answer, does not matter what is it, set of get.

I tested this issue with another services (i.e. pm2 manager), and saw the same problem.

**Comment by MaxSvargal** [comment]
I found a problem in balancer.
When I connect any other responder to the cluster, with another commands in respondsTo, a part of requests passed to it!

**Comment by dashersw** [comment]
@MaxSvargal so this is already documented behavior; and the explanation and the solution is as follows:

> Note: By default, every Requester will connect to every Responder it discovers, regardless of the request type. This means, every Responder should respond to the exact same set of requests, because Requesters will load-balance requests between all connected Responders regardless of their capabilities, i.e, whether or not they can handle a given request.

> If you have multiple Responders with varying response handlers, you will experience lost requests. In cote, this separation between responsibilities is called segmentation, or partitioning. If you wish to segment your requests in groups, you can use keys. Check out keys for a detailed guide on how and when to use segmentation.

https://github.com/dashersw/cote#keys

**Comment by MaxSvargal** [comment]
@dashersw sorry, i didn't see that part of docs =(
