### ISSUE TITLE
connect EADDRNOTAVAIL 0.0.0.0:8000

### ISSUE THREAD

**Issue by wanglong167** [dashersw/cote#74]
`var cote = require('cote')({ redis: {
  host: "localhost"
}});

//no auth
const timeService = new cote.Responder({name: 'Time Service'});

timeService.on('time', (req, cb) => {
    cb(new Date());
});

const client = new cote.Requester({name: 'Client'});

client.send({type: 'time'}, (time) => {
    console.log(time);
});`

**Comment by dashersw** [comment]
Which environment are you in? Your code works for me.

**Comment by wanglong167** [comment]
@dashersw  Is there a connection redis example  ,Redis support auth

**Comment by wanglong167** [comment]
window  no
mac ok

**Comment by sdeceuninck** [comment]
Hello,
same problem here on windows.

But if I launch first the requester, the requester starts fine. When the responder (the time service) comes online, the requester failed with a message of addr not available on port 8001. But the requester seems to work well.
![image](https://user-images.githubusercontent.com/4398285/38171619-375d4064-359d-11e8-8fb2-d7cda64ad379.png)
It's like the responder has a kind of priority ..

If I remove the redis part, everything works as expected.

Thanks

**Comment by sdeceuninck** [comment]
Just a question : does someone will take this issue to develop a fix or is it going to never work on windows instance ?

**Comment by dashersw** [comment]
@sdeceuninck I cannot reproduce the issue on Windows. I will try again.

**Comment by sdeceuninck** [comment]
Thanks @dashersw .

May it come from redis ? My redis was also on windows. I'll try with a redis on linux instead. I let you know.
