### ISSUE TITLE
Broadcast to certain group of users thought Sockend

### ISSUE THREAD

**Issue by VMois** [dashersw/cote#75]
Do Cote provides any mechanism to broadcast not to all, but to a certain group of users through Sockend? Thanks.

**Comment by dashersw** [comment]
Hello @VMois , the only automatic way to achieve that is to use different namespaces.

However if you want to delve deeper, you can manually decide whom to send a message to by effectively reaching out the underlying socket.io connection.

**Comment by VMois** [comment]
Thanks, @dashersw . Could I use socket.io rooms?
