### ISSUE TITLE
How to run multiple micro servers without defined the ports?

### ISSUE THREAD

**Issue by roysG** [dashersw/cote#76]
I have 3 micro services:
payments,
showInfo,
ListOfPayment
Each one is run as micro server.

As i understand 'cote" is working without needing to set default port.
How can i run each micro service without define port?

**Comment by dashersw** [comment]
Hello @roysG, just run them in separate terminals / background / with pm2 / with docker.

It will work :)

**Comment by roysG** [comment]
Hi @dashersw, 
Thanks for your quick response.
Just to understand, i need to define some api route, can i define it with "cote" or needs to install "express" for that use?

**Comment by dashersw** [comment]
cote can act as a WebSockets API out of the box. For using it with HTTP APIs, check out here: https://github.com/dashersw/cote-workshop/blob/master/admin/server.js

**Comment by roysG** [comment]
So if i understood it right, 
i need to start at least 2 node server in different servers, to make some redundant to my api calls 
and then i can start micro servers as much as i need, right?

**Comment by dashersw** [comment]
Sure.

**Comment by roysG** [comment]
Ok, sound good.
So in my case do you think i need to work with docker?

**Comment by dashersw** [comment]
It's a good orchestration management tool, so I would recommend it. But you don't have to, I used cote without Docker for years.

**Comment by roysG** [comment]
The last question,
 i want to monitor all my micro process, do you have some recommandation for me?

**Comment by dashersw** [comment]
You could use PM2, datadog, or any other monitoring solution. Cote also comes with a preliminary monitoring service which you can start on the side. Example: https://github.com/dashersw/cote-workshop/blob/master/monitor.js

**Comment by roysG** [comment]
Tnx for your help man!

**Comment by roysG** [comment]
@dashersw , is there any difference if i scale 3 times micro service in the same service (with pm2)
in compare to run 3 different server and run just one process of the micro service

**Comment by dashersw** [comment]
Since the actual processing will take place in the microservice, it’s better to scale it. But make sure you don’t use cluster mode in pm2; its autoscaling shares ports and that’s a problem for cote.

**Comment by roysG** [comment]
Yee.. i also read about the problem with the cluster.

I also want to make some payment transaction and i little bit concern to using for that action with nodejs.

Cause as i see it, when i will do some upgrade to my payment service (in pm2 ) and restart it,  I never know if some user may be now in the middle of transaction and if yes i may stopped the process after he already done some payment steps.

So i think payment should do with php instead of nodejs.
I also curious for your opinion about that, thanks.

**Comment by dashersw** [comment]
Well, that's independent of the language you're using. If you update a php app the same way and restart it, you'll still lose requests.

Try graceful restarts to wait for the end of a transaction, or better yet make it stateless so any restart will pick up the transaction from where the previous process left off.

**Comment by brunofigalveskk** [comment]
I have a related issue. I have an API and in certain endpoints I want to send some data to be processed in a micro service. In localhost my responser and requester can "talk" but when I try to do it in a dev server they can't. Any suggestion?

**Comment by dashersw** [comment]
@brunofigalveskk where are you running the dev server?

**Comment by brunofigalveskk** [comment]
@dashersw on a ubuntu server

**Comment by dashersw** [comment]
Is it on your local machine, or on the cloud?

**Comment by brunofigalveskk** [comment]
Thank you. I will read with more attention the readme. But I have one more question let's assume that I will use redis as the central discovery. Does this approach still have advantages against queues?

**Comment by dashersw** [comment]
Of course, redis is a transparent replacement for the overlay network, it also doesn't carry actual messages, but only the discovery, so cote is still cote.
