### ISSUE TITLE
 Problem with monitoring.

### ISSUE THREAD

**Issue by Hatollint** [dashersw/cote#84]
When adding the monitor.js file to the project, I can not cite the cote network through the browser.
```
 # monitor.js
const cote = require('cote');

new cote.MonitoringTool(process.env.PORT || 8081);

```

After starting the network and this code, nothing happens.
![screenshot_16](https://user-images.githubusercontent.com/21129524/36906137-2d21840c-1e46-11e8-81dc-d9bf343f467e.png)

**Comment by dashersw** [comment]
@Hatollint did you make any progress on this issue? Could you share an example code? It won't show anything unless you have any other services, but I'm afraid there's something else here that doesn't work.
