### ISSUE TITLE
what is the `cb` argument on callback function

### ISSUE THREAD

**Issue by LucasBadico** [dashersw/cote#85]
A dummie question, I think.
This `cb` argument what is used to resolve the request stands for what?

**Comment by dashersw** [comment]
It’s the callback that you can use to provide a “reply” to the actual caller.

**Comment by LucasBadico** [comment]
Só cb is for CallBack ?

Em Sáb, 24 de mar de 2018 16:30, Armagan Amcalar <notifications@github.com>
escreveu:

**Comment by dashersw** [comment]
Yes.

**Comment by LucasBadico** [comment]
So, this would be more clear as in `fn`. 

```js
// this is from w3school
array.filter(function(currentValue, index, arr), thisValue)
```
I know that is a syntax suggar but I think that make everthing more clear.
```js
const rates = { usd_eur: 0.91, eur_usd: 1.10 };

responder.on('convert', (req, fn) => {
    fn(req.amount * rates[`${req.from}_${req.to}`]);
});
```

Also would as in a functional documentation.
Sorry if this is a minor issue, but with this clarification the framework became much more powerful to me.

Would be nice make this more clear in documentation.

**Comment by dashersw** [comment]
Callback is a familiar pattern in JavaScript, and It's already documented:

> Responding to a certain request, let's say convert, is the same as listening to the convert event, and handling it with a function that takes two parameters: a request and a callback. The request parameter holds information about a single request, and it's basically the same request object the requester above sent. The second parameter, the callback, expects to be called with the actual response.

**Comment by LucasBadico** [comment]
All right's than!
