### ISSUE TITLE
Add a GUI for Monitor component

### ISSUE THREAD

**Issue by dashersw** [dashersw/cote#9]
Currently the Monitor component works in CLI, which is not the best place to inspect tens of other components. There should be a Sockend component in Monitor to push the network information to a management frontend. The frontend should draw the mesh network in a dynamic fashion, such as with D3.

**Comment by ankakusu** [comment]
Do you have a sample data set to play with it?

**Comment by ankakusu** [comment]
Aren't we following the google styling rules for this repo?

**Comment by dashersw** [comment]
@ankakusu we do. why?

**Comment by ankakusu** [comment]
I run the linter and get back several errors.

**Comment by dashersw** [comment]
Closing in favor of #28
