### ISSUE TITLE
How do you secure Sockend?

### ISSUE THREAD

**Issue by ffocsi** [dashersw/cote#97]
Hello,

I am wondering how you're meant to authenticate Sockend with things like passport?

I was thinking maybe you can have a wrapper service where the request says which service it wants to go to but the only way to get through it is a Sockend security service which somehow can access the request context (I can't imagine how though).

Do you have any example of how you've done this please?

Thanks

**Comment by ffocsi** [comment]
I might have found the answer. Sockend namespaces. Just depends if the req object has what I need!

**Comment by dashersw** [comment]
Also, see requestTransformators array on the sockend. This is for implementing access control or modifying the original request (for example for adding session / user info) before you pass it on to other components.

**Comment by ffocsi** [comment]
Thanks. This might sound a silly question but does the name having the word responder/requester/sockend in it have any significance? Like does a requester have to be called e.g. "Dog Requester" and "Dog Responder" or can it be like "dog client" and "dog service"?

**Comment by dashersw** [comment]
No problem, the name can be anything you like.
