### ISSUE TITLE
async/await on Requester ? 

### ISSUE THREAD

**Issue by eliascalabrese** [dashersw/cote#98]
Hi !
I am trying to add async/await to get data from specific service. Here is my code where I implemented but seems to be wrong, I get the response after cb() have been send.

It this a correct way to use cote js  ( Account Service and Comments Service ) ? 

`commentList.map(async comment => {
        await accountResquester.send({ type: 'account-profile', account: { _id: comment.owner } }, response => {
          comment.owner = response;
        });
        return comment;
      });`

Thanks.

**Comment by dashersw** [comment]
Regular array methods like .map doesn’t work out of the box with async / await. That might be your problem here.

**Comment by pawel-miczka** [comment]
Hope it helps:

```js
(async () => {
  let index = 0;
  await Promise.all([1, 2, 3].map(async e => {
  	index++;
  }));
  console.log(index); // 3 in console
})();
```
