### ISSUE TITLE
Two Requester instances in one process, not selecting master

### ISSUE THREAD

**Issue by rysi3k** [dashersw/cote#99]
Hello,
I have problem with configuring two Requester instances on one node process.
I set different key field on each Requester, then listening on "master" or "promote" event from node-discover and it causes weird result.
For first Requester instance, master is selected, but for other is not.
Here is exmaple script:
```
const cote = require('cote')({log: false});

const handleMasterChange = (client, discovery, masterHost) => {
    const {id, advertisement: {key}} = discovery.me;

    if (masterHost.advertisement.key !== key) {
        console.log(`[${client}][${id}] skipped wrong key ${masterHost.advertisement.key}`);
        return;
    }

    console.log(`[${client}][${id}] selected masterId=${masterHost.id}`);
    if (masterHost.id === id) {
        console.log(`[${client}][${id}] setup as MASTER`);
    } else {
        console.log(`[${client}][${id}] setup as slave`);
    }
}

const clientA = new cote.Requester({name: 'clientA', key: 'A'});
console.log(`[A] is ${clientA.discovery.me.id}`);
clientA.discovery.on('master', (...args) => handleMasterChange('A', clientA.discovery, ...args));
clientA.discovery.on('promotion', (...args) => handleMasterChange('A', clientA.discovery, ...args));

const clientB = new cote.Requester({name: 'clientB', key: 'B'});
console.log(`[B] is ${clientB.discovery.me.id}`);
clientB.discovery.on('master', (...args) => handleMasterChange('B', clientB.discovery, ...args));
clientB.discovery.on('promotion', (...args) => handleMasterChange('B', clientB.discovery, ...args));
```

output:
```
[A] is 75742456-e9e3-4e56-b7d7-2289ae22ac3b
[B] is 7b6b5818-f299-4655-8efa-ed8845c7df7f
[A][75742456-e9e3-4e56-b7d7-2289ae22ac3b] selected masterId=75742456-e9e3-4e56-b7d7-2289ae22ac3b
[A][75742456-e9e3-4e56-b7d7-2289ae22ac3b] setup as MASTER
[B][7b6b5818-f299-4655-8efa-ed8845c7df7f] skipped wrong key $$A
```
I'm missing something or what?
I expected that for "B" there also should be line "setup as MASTER".
Why there is "skipped wrong key $$A", shouldnt both instances be separated?

Regards
Tomasz

**Comment by dashersw** [comment]
Hello Tomasz, master selection and promotion is an internal mechanism in cote and that doesn't actually work, as you have come across. cote's approach is on redundancy and high-availability. Your application / use case shouldn't depend on master selection — instead, it should be stateless. Regardless of how many requesters / responders there are in a system, it should work equally well.

**Comment by dashersw** [comment]
A technical detail here is; cote's discovery mechanism is at a lower level than `key`s; so even though your requesters have different `key`s, they still discover each other and thus are eligible for master selection / promotion. Again, it's an unused, internal feature.
